// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/ParserLexer/lexer.jflex

/* https://www.jflex.de/manual.html */
/* JFlex example: partial Java language lexer specification */
package ParserLexer;
import java.io.StringReader;
import java_cup.runtime.*;

/*Declaraciones y opciones*/

@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int ERROR = 4;
  public static final int DECREMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\3\0\1\11\2\0\1\12\1\6"+
    "\1\13\1\14\1\15\1\16\1\17\11\20\7\0\4\21"+
    "\1\22\25\21\1\6\1\23\1\6\1\0\1\24\1\0"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\2\21\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\3\6\7\0\1\3\64\0\1\55\10\0\1\56"+
    "\u0164\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\3\2\1\1\1\3\1\2\1\4\1\5"+
    "\2\1\2\6\25\1\1\7\1\10\1\0\1\10\1\0"+
    "\2\6\1\2\2\10\1\6\3\10\1\11\44\10\1\12"+
    "\2\13\2\0\1\2\1\10\1\6\2\0\52\10\2\6"+
    "\1\0\1\10\2\0\12\10\1\14\11\10\1\15\3\10"+
    "\1\16\13\10\1\17\2\10\1\20\1\10\1\0\11\10"+
    "\1\21\3\10\1\22\3\10\1\23\5\10\1\24\2\10"+
    "\1\25\3\10\1\26\1\27\1\10\1\30\15\10\1\12"+
    "\1\31\5\10\1\32\1\33\11\10\1\34\1\10\1\35"+
    "\13\10\1\36\1\10\1\37\4\10\1\40\1\41\1\42"+
    "\2\10\1\43\1\10\1\44\1\45\1\46\3\10\1\47"+
    "\1\50\1\51\3\10\1\52\2\10\1\53\2\10\1\54"+
    "\1\55\6\10\1\56\1\57\2\10\1\60\1\10\1\61"+
    "\4\10\1\62\1\63\3\10\1\64\1\65\1\10\1\66"+
    "\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[328];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\215\0\353\0\274"+
    "\0\u011a\0\u0149\0\u0178\0\274\0\u01a7\0\u01d6\0\u0205\0\u0234"+
    "\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac"+
    "\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5\0\u0524"+
    "\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\274\0\215\0\u063e"+
    "\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6"+
    "\0\u07e5\0\u0814\0\u0843\0\215\0\u0872\0\u08a1\0\u08d0\0\u08ff"+
    "\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77"+
    "\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef"+
    "\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67"+
    "\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf"+
    "\0\u063e\0\215\0\274\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca"+
    "\0\u0ff9\0\u1028\0\u0263\0\u1057\0\u1086\0\u10b5\0\u10e4\0\u1113"+
    "\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\u122d\0\u125c\0\u128b"+
    "\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u1376\0\u13a5\0\u13d4\0\u1403"+
    "\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee\0\u151d\0\u154c\0\u157b"+
    "\0\u15aa\0\u15d9\0\u1608\0\u1637\0\u1666\0\u1695\0\u16c4\0\u16f3"+
    "\0\u1722\0\u1751\0\u1780\0\u17af\0\u17de\0\u0ff9\0\u180d\0\u183c"+
    "\0\u186b\0\u189a\0\u18c9\0\u18f8\0\u1927\0\u1956\0\u1985\0\u19b4"+
    "\0\u19e3\0\u1a12\0\u1a41\0\u1a70\0\215\0\u1a9f\0\u1ace\0\u1afd"+
    "\0\u1b2c\0\u1b5b\0\u1b8a\0\u1bb9\0\u1be8\0\u1c17\0\215\0\u1c46"+
    "\0\u1c75\0\u1ca4\0\215\0\u1cd3\0\u1d02\0\u1d31\0\u1d60\0\u1d8f"+
    "\0\u1dbe\0\u1ded\0\u1e1c\0\u1e4b\0\u1e7a\0\u1ea9\0\u1ed8\0\u1f07"+
    "\0\u1f36\0\215\0\u1f65\0\u1f94\0\u1fc3\0\u1ff2\0\u2021\0\u2050"+
    "\0\u207f\0\u20ae\0\u20dd\0\u210c\0\u213b\0\215\0\u216a\0\u2199"+
    "\0\u21c8\0\215\0\u21f7\0\u2226\0\u2255\0\215\0\u2284\0\u22b3"+
    "\0\u22e2\0\u2311\0\u2340\0\215\0\u236f\0\u239e\0\215\0\u23cd"+
    "\0\u23fc\0\u242b\0\215\0\215\0\u245a\0\215\0\u2489\0\u24b8"+
    "\0\u24e7\0\u2516\0\u2545\0\u2574\0\u25a3\0\u25d2\0\u2601\0\u2630"+
    "\0\u265f\0\u268e\0\u26bd\0\215\0\215\0\u26ec\0\u271b\0\u274a"+
    "\0\u2779\0\u27a8\0\215\0\215\0\u27d7\0\u2806\0\u2835\0\u2864"+
    "\0\u2893\0\u28c2\0\u28f1\0\u2920\0\u294f\0\215\0\u297e\0\215"+
    "\0\u29ad\0\u29dc\0\u2a0b\0\u2a3a\0\u2a69\0\u2a98\0\u2ac7\0\u2af6"+
    "\0\u2b25\0\u2b54\0\u2b83\0\215\0\u2bb2\0\215\0\u2be1\0\u2c10"+
    "\0\u2c3f\0\u2c6e\0\215\0\215\0\215\0\u2c9d\0\u2ccc\0\215"+
    "\0\u2cfb\0\215\0\215\0\215\0\u2d2a\0\u2d59\0\u2d88\0\215"+
    "\0\215\0\215\0\u2db7\0\u2de6\0\u2e15\0\215\0\u2e44\0\u2e73"+
    "\0\215\0\u2ea2\0\u2ed1\0\215\0\215\0\u2f00\0\u2f2f\0\u2f5e"+
    "\0\u2f8d\0\u2fbc\0\u2feb\0\215\0\215\0\u301a\0\u3049\0\215"+
    "\0\u3078\0\215\0\u30a7\0\u30d6\0\u3105\0\u3134\0\215\0\215"+
    "\0\u3163\0\u3192\0\u31c1\0\215\0\215\0\u31f0\0\215\0\215";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[328];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\4\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\4\1\14\1\15\1\4\1\16\1\17\1\20"+
    "\2\4\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\4\1\34\1\35\1\36"+
    "\1\4\1\37\1\40\1\41\1\42\1\43\1\44\5\4"+
    "\1\45\57\46\1\4\2\10\2\4\4\10\2\4\2\10"+
    "\42\4\1\47\2\0\2\47\4\0\2\47\2\0\42\47"+
    "\61\0\1\5\54\0\2\50\4\0\51\50\2\12\1\5"+
    "\54\12\1\51\1\52\1\0\2\47\1\0\3\52\2\51"+
    "\2\52\42\51\17\0\1\53\1\54\36\0\1\47\2\0"+
    "\2\47\4\0\2\47\2\0\1\47\1\55\4\47\1\56"+
    "\34\47\2\0\2\47\4\0\2\47\2\0\1\57\1\47"+
    "\2\60\1\47\1\61\6\47\1\61\26\47\2\0\2\47"+
    "\4\0\2\47\2\0\1\57\1\47\2\20\1\47\1\61"+
    "\6\47\1\61\26\47\2\0\2\47\4\0\2\47\2\0"+
    "\7\47\1\62\33\47\2\0\2\47\4\0\2\47\2\0"+
    "\2\47\4\63\1\47\1\64\23\63\1\65\4\63\3\47"+
    "\2\0\2\47\4\0\2\47\2\0\11\47\1\66\1\47"+
    "\1\67\27\47\2\0\2\47\4\0\2\47\2\0\10\47"+
    "\1\70\16\47\1\71\13\47\2\0\2\47\4\0\2\47"+
    "\2\0\20\47\1\72\3\47\1\73\5\47\1\74\10\47"+
    "\2\0\2\47\4\0\2\47\2\0\32\47\1\75\10\47"+
    "\2\0\2\47\4\0\2\47\2\0\21\47\1\76\1\47"+
    "\1\77\4\47\1\100\2\47\1\101\7\47\2\0\2\47"+
    "\4\0\2\47\2\0\10\47\1\102\7\47\1\103\22\47"+
    "\2\0\2\47\4\0\2\47\2\0\10\47\1\104\16\47"+
    "\1\105\13\47\2\0\2\47\4\0\2\47\2\0\10\47"+
    "\1\106\7\47\1\107\22\47\2\0\2\47\4\0\2\47"+
    "\2\0\23\47\1\110\17\47\2\0\2\47\4\0\2\47"+
    "\2\0\10\47\1\111\3\47\1\112\3\47\1\113\22\47"+
    "\2\0\2\47\4\0\2\47\2\0\10\47\1\114\13\47"+
    "\1\115\16\47\2\0\2\47\4\0\2\47\2\0\25\47"+
    "\1\116\15\47\2\0\2\47\4\0\2\47\2\0\32\47"+
    "\1\117\10\47\2\0\2\47\4\0\2\47\2\0\14\47"+
    "\1\120\7\47\1\121\16\47\2\0\2\47\4\0\2\47"+
    "\2\0\20\47\1\122\2\47\1\123\17\47\2\0\2\47"+
    "\4\0\2\47\2\0\27\47\1\124\13\47\2\0\2\47"+
    "\4\0\2\47\2\0\25\47\1\125\15\47\2\0\2\47"+
    "\4\0\2\47\2\0\10\47\1\126\13\47\1\127\16\47"+
    "\2\0\2\47\4\0\2\47\2\0\40\47\1\130\1\47"+
    "\2\50\4\0\1\50\1\131\47\50\1\47\2\0\2\47"+
    "\4\0\1\132\1\47\2\0\42\47\11\0\1\133\62\0"+
    "\1\134\4\0\1\135\6\0\1\135\42\0\1\134\1\0"+
    "\2\54\1\0\1\135\6\0\1\135\25\0\1\55\1\136"+
    "\1\0\2\47\1\0\3\136\2\55\2\136\42\55\1\47"+
    "\2\0\2\47\4\0\1\47\1\137\2\0\43\47\2\0"+
    "\2\47\4\0\2\47\2\0\2\47\2\140\37\47\2\0"+
    "\2\47\4\0\2\47\2\0\2\47\2\60\37\47\2\0"+
    "\2\47\4\0\2\47\1\0\1\141\2\47\2\60\36\47"+
    "\1\62\2\142\2\62\4\142\2\62\2\142\6\62\1\143"+
    "\1\144\32\62\1\47\2\0\2\47\4\0\2\47\2\0"+
    "\2\47\4\63\1\47\1\64\30\63\3\47\2\0\2\47"+
    "\4\0\2\47\2\0\2\47\4\63\1\47\1\64\4\63"+
    "\1\145\23\63\3\47\2\0\2\47\4\0\2\47\2\0"+
    "\27\47\1\146\13\47\2\0\2\47\4\0\2\47\2\0"+
    "\33\47\1\147\7\47\2\0\2\47\4\0\2\47\2\0"+
    "\21\47\1\150\21\47\2\0\2\47\4\0\2\47\2\0"+
    "\24\47\1\151\16\47\2\0\2\47\4\0\2\47\2\0"+
    "\14\47\1\152\26\47\2\0\2\47\4\0\2\47\2\0"+
    "\22\47\1\153\4\47\1\154\13\47\2\0\2\47\4\0"+
    "\2\47\2\0\25\47\1\155\15\47\2\0\2\47\4\0"+
    "\2\47\2\0\14\47\1\156\26\47\2\0\2\47\4\0"+
    "\2\47\2\0\15\47\1\157\25\47\2\0\2\47\4\0"+
    "\2\47\2\0\31\47\1\160\1\47\1\161\7\47\2\0"+
    "\2\47\4\0\2\47\2\0\12\47\1\162\30\47\2\0"+
    "\2\47\4\0\2\47\2\0\14\47\1\163\26\47\2\0"+
    "\2\47\4\0\2\47\2\0\21\47\1\164\21\47\2\0"+
    "\2\47\4\0\2\47\2\0\23\47\1\165\17\47\2\0"+
    "\2\47\4\0\2\47\2\0\30\47\1\166\12\47\2\0"+
    "\2\47\4\0\2\47\2\0\20\47\1\167\22\47\2\0"+
    "\2\47\4\0\2\47\2\0\13\47\1\170\27\47\2\0"+
    "\2\47\4\0\2\47\2\0\30\47\1\171\12\47\2\0"+
    "\2\47\4\0\2\47\2\0\31\47\1\172\11\47\2\0"+
    "\2\47\4\0\2\47\2\0\16\47\1\173\10\47\1\174"+
    "\13\47\2\0\2\47\4\0\2\47\2\0\21\47\1\175"+
    "\21\47\2\0\2\47\4\0\2\47\2\0\23\47\1\176"+
    "\17\47\2\0\2\47\4\0\2\47\2\0\27\47\1\177"+
    "\3\47\1\200\7\47\2\0\2\47\4\0\2\47\2\0"+
    "\12\47\1\201\30\47\2\0\2\47\4\0\2\47\2\0"+
    "\14\47\1\202\26\47\2\0\2\47\4\0\2\47\2\0"+
    "\20\47\1\203\22\47\2\0\2\47\4\0\2\47\2\0"+
    "\36\47\1\204\4\47\2\0\2\47\4\0\2\47\2\0"+
    "\13\47\1\205\27\47\2\0\2\47\4\0\2\47\2\0"+
    "\16\47\1\206\24\47\2\0\2\47\4\0\2\47\2\0"+
    "\24\47\1\207\16\47\2\0\2\47\4\0\2\47\2\0"+
    "\32\47\1\210\10\47\2\0\2\47\4\0\2\47\2\0"+
    "\10\47\1\211\32\47\2\0\2\47\4\0\2\47\2\0"+
    "\27\47\1\212\13\47\2\0\2\47\4\0\2\47\2\0"+
    "\20\47\1\213\22\47\2\0\2\47\4\0\2\47\2\0"+
    "\21\47\1\214\20\47\17\0\2\215\52\0\1\141\2\0"+
    "\2\216\36\0\2\136\4\0\51\136\1\137\2\217\2\137"+
    "\4\217\1\137\1\47\2\217\6\137\1\220\33\137\1\47"+
    "\2\0\2\47\4\0\2\47\2\0\2\47\2\140\1\47"+
    "\1\61\6\47\1\61\25\47\17\0\2\216\36\0\23\142"+
    "\1\221\1\222\32\142\1\47\2\0\2\47\4\0\2\47"+
    "\2\0\1\47\1\6\41\47\2\0\2\47\4\0\2\47"+
    "\2\0\2\47\4\63\1\47\1\64\17\63\1\223\10\63"+
    "\3\47\2\0\2\47\4\0\2\47\2\0\14\47\1\224"+
    "\26\47\2\0\2\47\4\0\2\47\2\0\20\47\1\225"+
    "\22\47\2\0\2\47\4\0\2\47\2\0\31\47\1\226"+
    "\11\47\2\0\2\47\4\0\2\47\2\0\22\47\1\227"+
    "\20\47\2\0\2\47\4\0\2\47\2\0\27\47\1\230"+
    "\13\47\2\0\2\47\4\0\2\47\2\0\14\47\1\231"+
    "\26\47\2\0\2\47\4\0\2\47\2\0\31\47\1\232"+
    "\11\47\2\0\2\47\4\0\2\47\2\0\20\47\1\233"+
    "\22\47\2\0\2\47\4\0\2\47\2\0\23\47\1\234"+
    "\17\47\2\0\2\47\4\0\2\47\2\0\24\47\1\235"+
    "\16\47\2\0\2\47\4\0\2\47\2\0\27\47\1\236"+
    "\13\47\2\0\2\47\4\0\2\47\2\0\20\47\1\237"+
    "\11\47\1\240\10\47\2\0\2\47\4\0\2\47\2\0"+
    "\32\47\1\241\10\47\2\0\2\47\4\0\2\47\2\0"+
    "\27\47\1\242\13\47\2\0\2\47\4\0\2\47\2\0"+
    "\30\47\1\243\12\47\2\0\2\47\4\0\2\47\2\0"+
    "\27\47\1\244\13\47\2\0\2\47\4\0\2\47\2\0"+
    "\25\47\1\245\15\47\2\0\2\47\4\0\2\47\2\0"+
    "\23\47\1\246\17\47\2\0\2\47\4\0\2\47\2\0"+
    "\10\47\1\247\32\47\2\0\2\47\4\0\2\47\2\0"+
    "\31\47\1\250\11\47\2\0\2\47\4\0\2\47\2\0"+
    "\14\47\1\251\26\47\2\0\2\47\4\0\2\47\2\0"+
    "\24\47\1\252\16\47\2\0\2\47\4\0\2\47\2\0"+
    "\36\47\1\253\4\47\2\0\2\47\4\0\2\47\2\0"+
    "\12\47\1\254\30\47\2\0\2\47\4\0\2\47\2\0"+
    "\30\47\1\255\12\47\2\0\2\47\4\0\2\47\2\0"+
    "\27\47\1\256\13\47\2\0\2\47\4\0\2\47\2\0"+
    "\20\47\1\257\22\47\2\0\2\47\4\0\2\47\2\0"+
    "\17\47\1\260\23\47\2\0\2\47\4\0\2\47\2\0"+
    "\23\47\1\261\17\47\2\0\2\47\4\0\2\47\2\0"+
    "\14\47\1\262\26\47\2\0\2\47\4\0\2\47\2\0"+
    "\14\47\1\263\26\47\2\0\2\47\4\0\2\47\2\0"+
    "\24\47\1\264\16\47\2\0\2\47\4\0\2\47\2\0"+
    "\32\47\1\265\10\47\2\0\2\47\4\0\2\47\2\0"+
    "\34\47\1\266\6\47\2\0\2\47\4\0\2\47\2\0"+
    "\14\47\1\267\26\47\2\0\2\47\4\0\2\47\2\0"+
    "\31\47\1\270\11\47\2\0\2\47\4\0\2\47\2\0"+
    "\20\47\1\271\22\47\2\0\2\47\4\0\2\47\2\0"+
    "\13\47\1\272\27\47\2\0\2\47\4\0\2\47\2\0"+
    "\31\47\1\273\10\47\17\0\2\215\1\0\1\135\6\0"+
    "\1\135\25\0\12\217\1\0\10\217\1\274\33\217\1\137"+
    "\2\217\2\137\4\217\1\137\1\144\2\217\6\137\1\220"+
    "\33\137\24\0\1\142\50\0\1\5\40\0\1\47\2\0"+
    "\2\47\4\0\2\47\2\0\2\47\4\63\1\47\1\64"+
    "\1\275\27\63\3\47\2\0\2\47\4\0\2\47\2\0"+
    "\12\47\1\276\1\47\1\277\12\47\1\300\13\47\2\0"+
    "\2\47\4\0\2\47\2\0\14\47\1\301\26\47\2\0"+
    "\2\47\4\0\2\47\2\0\10\47\1\302\32\47\2\0"+
    "\2\47\4\0\2\47\2\0\20\47\1\303\22\47\2\0"+
    "\2\47\4\0\2\47\2\0\27\47\1\304\13\47\2\0"+
    "\2\47\4\0\2\47\2\0\31\47\1\305\11\47\2\0"+
    "\2\47\4\0\2\47\2\0\10\47\1\306\32\47\2\0"+
    "\2\47\4\0\2\47\2\0\13\47\1\307\27\47\2\0"+
    "\2\47\4\0\2\47\2\0\13\47\1\310\27\47\2\0"+
    "\2\47\4\0\2\47\2\0\14\47\1\311\26\47\2\0"+
    "\2\47\4\0\2\47\2\0\10\47\1\312\32\47\2\0"+
    "\2\47\4\0\2\47\2\0\14\47\1\313\26\47\2\0"+
    "\2\47\4\0\2\47\2\0\12\47\1\314\30\47\2\0"+
    "\2\47\4\0\2\47\2\0\16\47\1\315\24\47\2\0"+
    "\2\47\4\0\2\47\2\0\14\47\1\316\26\47\2\0"+
    "\2\47\4\0\2\47\2\0\14\47\1\317\26\47\2\0"+
    "\2\47\4\0\2\47\2\0\10\47\1\320\32\47\2\0"+
    "\2\47\4\0\2\47\2\0\12\47\1\321\30\47\2\0"+
    "\2\47\4\0\2\47\2\0\24\47\1\322\16\47\2\0"+
    "\2\47\4\0\2\47\2\0\27\47\1\323\13\47\2\0"+
    "\2\47\4\0\2\47\2\0\30\47\1\324\12\47\2\0"+
    "\2\47\4\0\2\47\2\0\17\47\1\325\23\47\2\0"+
    "\2\47\4\0\2\47\2\0\31\47\1\326\11\47\2\0"+
    "\2\47\4\0\2\47\2\0\10\47\1\327\32\47\2\0"+
    "\2\47\4\0\2\47\2\0\13\47\1\330\27\47\2\0"+
    "\2\47\4\0\2\47\2\0\14\47\1\331\26\47\2\0"+
    "\2\47\4\0\2\47\2\0\30\47\1\332\12\47\2\0"+
    "\2\47\4\0\2\47\2\0\23\47\1\333\17\47\2\0"+
    "\2\47\4\0\2\47\2\0\30\47\1\334\12\47\2\0"+
    "\2\47\4\0\2\47\2\0\21\47\1\335\21\47\2\0"+
    "\2\47\4\0\2\47\2\0\14\47\1\336\26\47\2\0"+
    "\2\47\4\0\2\47\2\0\11\47\1\337\31\47\2\0"+
    "\2\47\4\0\2\47\2\0\23\47\1\340\17\47\2\0"+
    "\2\47\4\0\2\47\2\0\27\47\1\341\13\47\2\0"+
    "\2\47\4\0\2\47\2\0\24\47\1\342\16\47\2\0"+
    "\2\47\4\0\2\47\2\0\20\47\1\343\21\47\12\217"+
    "\1\222\10\217\1\274\33\217\1\47\2\0\2\47\4\0"+
    "\2\47\2\0\2\47\4\63\1\47\1\64\13\63\1\344"+
    "\14\63\3\47\2\0\2\47\4\0\2\47\2\0\32\47"+
    "\1\345\10\47\2\0\2\47\4\0\2\47\2\0\22\47"+
    "\1\346\20\47\2\0\2\47\4\0\2\47\2\0\14\47"+
    "\1\347\26\47\2\0\2\47\4\0\2\47\2\0\23\47"+
    "\1\350\17\47\2\0\2\47\4\0\2\47\2\0\37\47"+
    "\1\351\3\47\2\0\2\47\4\0\2\47\2\0\30\47"+
    "\1\352\12\47\2\0\2\47\4\0\2\47\2\0\10\47"+
    "\1\353\32\47\2\0\2\47\4\0\2\47\2\0\10\47"+
    "\1\354\32\47\2\0\2\47\4\0\2\47\2\0\24\47"+
    "\1\132\16\47\2\0\2\47\4\0\2\47\2\0\14\47"+
    "\1\355\26\47\2\0\2\47\4\0\2\47\2\0\16\47"+
    "\1\356\24\47\2\0\2\47\4\0\2\47\2\0\21\47"+
    "\1\357\21\47\2\0\2\47\4\0\2\47\2\0\17\47"+
    "\1\360\23\47\2\0\2\47\4\0\2\47\2\0\27\47"+
    "\1\361\13\47\2\0\2\47\4\0\2\47\2\0\16\47"+
    "\1\362\24\47\2\0\2\47\4\0\2\47\2\0\27\47"+
    "\1\363\13\47\2\0\2\47\4\0\2\47\2\0\17\47"+
    "\1\364\23\47\2\0\2\47\4\0\2\47\2\0\27\47"+
    "\1\365\13\47\2\0\2\47\4\0\2\47\2\0\12\47"+
    "\1\366\30\47\2\0\2\47\4\0\2\47\2\0\24\47"+
    "\1\367\16\47\2\0\2\47\4\0\2\47\2\0\20\47"+
    "\1\370\22\47\2\0\2\47\4\0\2\47\2\0\10\47"+
    "\1\371\32\47\2\0\2\47\4\0\2\47\2\0\11\47"+
    "\1\372\31\47\2\0\2\47\4\0\2\47\2\0\21\47"+
    "\1\373\21\47\2\0\2\47\4\0\2\47\2\0\15\47"+
    "\1\374\25\47\2\0\2\47\4\0\2\47\2\0\10\47"+
    "\1\375\32\47\2\0\2\47\4\0\2\47\2\0\24\47"+
    "\1\376\16\47\2\0\2\47\4\0\2\47\2\0\14\47"+
    "\1\377\26\47\2\0\2\47\4\0\2\47\2\0\30\47"+
    "\1\u0100\12\47\2\0\2\47\4\0\2\47\2\0\22\47"+
    "\1\u0101\20\47\2\0\2\47\4\0\2\47\2\0\2\47"+
    "\4\63\1\47\1\64\14\63\1\u0102\13\63\3\47\2\0"+
    "\2\47\4\0\2\47\2\0\14\47\1\u0103\26\47\2\0"+
    "\2\47\4\0\2\47\2\0\25\47\1\u0104\15\47\2\0"+
    "\2\47\4\0\2\47\2\0\16\47\1\u0105\24\47\2\0"+
    "\2\47\4\0\2\47\2\0\31\47\1\u0106\11\47\2\0"+
    "\2\47\4\0\2\47\2\0\10\47\1\u0107\32\47\2\0"+
    "\2\47\4\0\2\47\2\0\31\47\1\u0108\11\47\2\0"+
    "\2\47\4\0\2\47\2\0\12\47\1\u0109\1\47\1\u010a"+
    "\12\47\1\u010b\13\47\2\0\2\47\4\0\2\47\2\0"+
    "\10\47\1\u010c\32\47\2\0\2\47\4\0\2\47\2\0"+
    "\33\47\1\u010d\7\47\2\0\2\47\4\0\2\47\2\0"+
    "\10\47\1\u010e\32\47\2\0\2\47\4\0\2\47\2\0"+
    "\14\47\1\u010f\26\47\2\0\2\47\4\0\2\47\2\0"+
    "\10\47\1\u0110\32\47\2\0\2\47\4\0\2\47\2\0"+
    "\20\47\1\u0111\22\47\2\0\2\47\4\0\2\47\2\0"+
    "\10\47\1\u0112\32\47\2\0\2\47\4\0\2\47\2\0"+
    "\27\47\1\u0113\13\47\2\0\2\47\4\0\2\47\2\0"+
    "\35\47\1\u0114\5\47\2\0\2\47\4\0\2\47\2\0"+
    "\13\47\1\u0115\27\47\2\0\2\47\4\0\2\47\2\0"+
    "\32\47\1\u0116\10\47\2\0\2\47\4\0\2\47\2\0"+
    "\10\47\1\u0117\32\47\2\0\2\47\4\0\2\47\2\0"+
    "\24\47\1\u0118\16\47\2\0\2\47\4\0\2\47\2\0"+
    "\21\47\1\u0119\21\47\2\0\2\47\4\0\2\47\2\0"+
    "\14\47\1\u011a\26\47\2\0\2\47\4\0\2\47\2\0"+
    "\24\47\1\u011b\16\47\2\0\2\47\4\0\2\47\2\0"+
    "\2\47\4\63\1\47\1\u011c\30\63\3\47\2\0\2\47"+
    "\4\0\2\47\2\0\23\47\1\u011d\17\47\2\0\2\47"+
    "\4\0\2\47\2\0\10\47\1\u011e\32\47\2\0\2\47"+
    "\4\0\2\47\2\0\10\47\1\u011f\32\47\2\0\2\47"+
    "\4\0\2\47\2\0\24\47\1\u0120\16\47\2\0\2\47"+
    "\4\0\2\47\2\0\27\47\1\u0121\13\47\2\0\2\47"+
    "\4\0\2\47\2\0\10\47\1\u0122\32\47\2\0\2\47"+
    "\4\0\2\47\2\0\32\47\1\u0123\10\47\2\0\2\47"+
    "\4\0\2\47\2\0\22\47\1\u0124\20\47\2\0\2\47"+
    "\4\0\2\47\2\0\14\47\1\u0125\26\47\2\0\2\47"+
    "\4\0\2\47\2\0\14\47\1\u0126\26\47\2\0\2\47"+
    "\4\0\2\47\2\0\14\47\1\u0127\26\47\2\0\2\47"+
    "\4\0\2\47\2\0\21\47\1\u0128\21\47\2\0\2\47"+
    "\4\0\2\47\2\0\10\47\1\u0129\32\47\2\0\2\47"+
    "\4\0\2\47\2\0\22\47\1\u012a\20\47\2\0\2\47"+
    "\4\0\2\47\2\0\14\47\1\u012b\26\47\2\0\2\47"+
    "\4\0\2\47\2\0\14\47\1\u012c\26\47\2\0\2\47"+
    "\4\0\2\47\2\0\21\47\1\u012d\21\47\2\0\2\47"+
    "\4\0\2\47\2\0\31\47\1\u012e\11\47\2\0\2\47"+
    "\4\0\2\47\2\0\26\47\1\u012f\14\47\2\0\2\47"+
    "\4\0\2\47\2\0\21\47\1\u0130\21\47\2\0\2\47"+
    "\4\0\2\47\2\0\14\47\1\u0131\26\47\2\0\2\47"+
    "\4\0\2\47\2\0\25\47\1\u0132\15\47\2\0\2\47"+
    "\4\0\2\47\2\0\16\47\1\u0133\24\47\2\0\2\47"+
    "\4\0\2\47\2\0\23\47\1\u0134\17\47\2\0\2\47"+
    "\4\0\2\47\2\0\24\47\1\u0135\16\47\2\0\2\47"+
    "\4\0\2\47\2\0\11\47\1\u0136\31\47\2\0\2\47"+
    "\4\0\2\47\2\0\23\47\1\u0137\17\47\2\0\2\47"+
    "\4\0\2\47\2\0\24\47\1\u0138\16\47\2\0\2\47"+
    "\4\0\2\47\2\0\32\47\1\u0139\10\47\2\0\2\47"+
    "\4\0\2\47\2\0\24\47\1\u013a\16\47\2\0\2\47"+
    "\4\0\2\47\2\0\23\47\1\u013b\17\47\2\0\2\47"+
    "\4\0\2\47\2\0\10\47\1\u013c\32\47\2\0\2\47"+
    "\4\0\2\47\2\0\10\47\1\u013d\32\47\2\0\2\47"+
    "\4\0\2\47\2\0\20\47\1\u013e\22\47\2\0\2\47"+
    "\4\0\2\47\2\0\10\47\1\u013f\32\47\2\0\2\47"+
    "\4\0\2\47\2\0\14\47\1\u0140\26\47\2\0\2\47"+
    "\4\0\2\47\2\0\31\47\1\u0141\11\47\2\0\2\47"+
    "\4\0\2\47\2\0\26\47\1\u0142\14\47\2\0\2\47"+
    "\4\0\2\47\2\0\21\47\1\u0143\21\47\2\0\2\47"+
    "\4\0\2\47\2\0\24\47\1\u0144\16\47\2\0\2\47"+
    "\4\0\2\47\2\0\24\47\1\u0145\16\47\2\0\2\47"+
    "\4\0\2\47\2\0\32\47\1\u0146\10\47\2\0\2\47"+
    "\4\0\2\47\2\0\24\47\1\u0147\16\47\2\0\2\47"+
    "\4\0\2\47\2\0\14\47\1\u0148\25\47";

  private static int [] zzUnpacktrans() {
    int [] result = new int[12831];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\1\1\11\2\1\1\11\3\1\1\11\31\1"+
    "\1\11\1\1\1\0\1\1\1\0\60\1\1\11\2\0"+
    "\3\1\2\0\54\1\1\0\1\1\2\0\51\1\1\0"+
    "\214\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[328];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    //string para imprimir los contenidos de los tokens encontrados
    StringBuffer string = new StringBuffer();
    private int errorCount = 0;

    //symbol predefinidos por el ejemplo proporcionado por jflex
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }

    //manejar errores y reportar
    private void handleError(String message) {
        System.err.println("ERROR: " + message + ", línea " + yyline + ", columna " + yycolumn);
        errorCount++;
    }

    public int getLine() {
        return yyline;
    }

    public int getColumn() {
        return yycolumn;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { yycolumn++;
        return symbol(sym.ERROR);
            }
          // fall through
          case 56: break;
          case 2:
            { 
            }
          // fall through
          case 57: break;
          case 3:
            { return symbol(sym.COMILLADOBLE);
            }
          // fall through
          case 58: break;
          case 4:
            { return symbol(sym.COMILLA);
            }
          // fall through
          case 59: break;
          case 5:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 60: break;
          case 6:
            { if(yytext().contains(".")) return symbol(sym.FLOAT, yytext()); else return symbol(sym.INTEGER, yytext());
            }
          // fall through
          case 61: break;
          case 7:
            { yycolumn++;
                                    return symbol(sym.ERROR);
            }
          // fall through
          case 62: break;
          case 8:
            { yycolumn += yylength();
    return symbol(sym.ERROR);
            }
          // fall through
          case 63: break;
          case 9:
            { return symbol(sym.IDENTIFICADOR, yytext());
            }
          // fall through
          case 64: break;
          case 10:
            { return symbol(sym.STRING, yytext());
            }
          // fall through
          case 65: break;
          case 11:
            { return symbol(sym.CHAR, yytext());
            }
          // fall through
          case 66: break;
          case 12:
            { return symbol(sym.IF);
            }
          // fall through
          case 67: break;
          case 13:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 68: break;
          case 14:
            { return symbol(sym.IGUALDAD);
            }
          // fall through
          case 69: break;
          case 15:
            { return symbol(sym.TRUE);
            }
          // fall through
          case 70: break;
          case 16:
            { return symbol(sym.VOID);
            }
          // fall through
          case 71: break;
          case 17:
            { return symbol(sym.BREAK);
            }
          // fall through
          case 72: break;
          case 18:
            { return symbol(sym.RETURN);
            }
          // fall through
          case 73: break;
          case 19:
            { return symbol(sym.FALSE);
            }
          // fall through
          case 74: break;
          case 20:
            { return symbol(sym.MODULO);
            }
          // fall through
          case 75: break;
          case 21:
            { return symbol(sym.PRINT);
            }
          // fall through
          case 76: break;
          case 22:
            { return symbol(sym.INCREMENTO);
            }
          // fall through
          case 77: break;
          case 23:
            { return symbol(sym.DIVISION);
            }
          // fall through
          case 78: break;
          case 24:
            { return symbol(sym.DOSPUNTOS, yytext());
            }
          // fall through
          case 79: break;
          case 25:
            { return symbol(sym.FOR);
            }
          // fall through
          case 80: break;
          case 26:
            { return symbol(sym.DISYUNCION);
            }
          // fall through
          case 81: break;
          case 27:
            { return symbol(sym.DECREMENTO);
            }
          // fall through
          case 82: break;
          case 28:
            { return symbol(sym.BOOL, yytext());
            }
          // fall through
          case 83: break;
          case 29:
            { return symbol(sym.SWITCH);
            }
          // fall through
          case 84: break;
          case 30:
            { return symbol(sym.ASIGNACION);
            }
          // fall through
          case 85: break;
          case 31:
            { return symbol(sym.READ);
            }
          // fall through
          case 86: break;
          case 32:
            { return symbol(sym.CONJUNCION);
            }
          // fall through
          case 87: break;
          case 33:
            { return symbol(sym.MAYOR);
            }
          // fall through
          case 88: break;
          case 34:
            { return symbol(sym.SUMA);
            }
          // fall through
          case 89: break;
          case 35:
            { return symbol(sym.INTEGER, yytext());
            }
          // fall through
          case 90: break;
          case 36:
            { return symbol(sym.MAYORIGUAL);
            }
          // fall through
          case 91: break;
          case 37:
            { return symbol(sym.DEFAULT);
            }
          // fall through
          case 92: break;
          case 38:
            { return symbol(sym.MAIN);
            }
          // fall through
          case 93: break;
          case 39:
            { return symbol(sym.POTENCIA);
            }
          // fall through
          case 94: break;
          case 40:
            { return symbol(sym.NEGACION);
            }
          // fall through
          case 95: break;
          case 41:
            { return symbol(sym.FLOAT, yytext());
            }
          // fall through
          case 96: break;
          case 42:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 97: break;
          case 43:
            { return symbol(sym.CASE);
            }
          // fall through
          case 98: break;
          case 44:
            { return symbol(sym.DIFERENTE);
            }
          // fall through
          case 99: break;
          case 45:
            { return symbol(sym.MENOR);
            }
          // fall through
          case 100: break;
          case 46:
            { return symbol(sym.MENORIGUAL);
            }
          // fall through
          case 101: break;
          case 47:
            { return symbol(sym.ENDEXPR);
            }
          // fall through
          case 102: break;
          case 48:
            { return symbol(sym.BRACEIZQ);
            }
          // fall through
          case 103: break;
          case 49:
            { return symbol(sym.PARENIZQ);
            }
          // fall through
          case 104: break;
          case 50:
            { return symbol(sym.MULTIPLICACION);
            }
          // fall through
          case 105: break;
          case 51:
            { return symbol(sym.CORCHETEIZQ);
            }
          // fall through
          case 106: break;
          case 52:
            { return symbol(sym.RESTA);
            }
          // fall through
          case 107: break;
          case 53:
            { return symbol(sym.BRACEDER);
            }
          // fall through
          case 108: break;
          case 54:
            { return symbol(sym.PARENDER);
            }
          // fall through
          case 109: break;
          case 55:
            { return symbol(sym.CORCHETEDER);
            }
          // fall through
          case 110: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
