// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/ParserLexer/lexer.jflex

/* https://www.jflex.de/manual.html */
/* JFlex example: partial Java language lexer specification */
package ParserLexer;
import java.io.StringReader;
import java_cup.runtime.*;

/*Declaraciones y opciones*/

@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int ERROR = 4;
  public static final int DECREMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  1,  1,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\3\0\1\11\2\0\1\12\1\0"+
    "\1\13\1\14\1\15\1\16\1\17\11\20\7\0\4\21"+
    "\1\22\25\21\1\0\1\23\2\0\1\24\1\0\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\2\21\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\12\0\1\3\64\0\1\55\10\0\1\56\u0164\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\1\1\4\1\5\2\0"+
    "\2\6\1\7\2\0\22\7\2\0\1\6\1\1\2\0"+
    "\1\6\3\0\1\10\1\0\41\7\1\0\1\7\1\0"+
    "\1\6\3\0\44\7\3\0\10\7\1\11\11\7\1\12"+
    "\3\7\1\13\13\7\1\14\2\7\2\0\7\7\1\15"+
    "\3\7\1\16\3\7\1\17\5\7\1\20\2\7\1\21"+
    "\3\7\1\22\1\23\1\7\1\24\4\7\2\0\7\7"+
    "\1\2\1\25\5\7\1\26\1\27\11\7\1\30\1\7"+
    "\1\31\2\0\11\7\1\32\1\7\1\33\4\7\1\34"+
    "\1\35\1\36\2\7\1\37\1\7\1\40\1\41\1\42"+
    "\3\7\1\43\1\44\1\45\3\7\1\46\2\7\1\47"+
    "\2\7\1\50\1\51\6\7\1\52\1\53\2\7\1\54"+
    "\1\7\1\55\4\7\1\56\1\57\3\7\1\60\1\61"+
    "\1\7\1\62\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[302];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\57\0\215\0\274\0\57"+
    "\0\57\0\353\0\u011a\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205"+
    "\0\u0234\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d"+
    "\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5"+
    "\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d"+
    "\0\u069c\0\u06cb\0\u06fa\0\u0729\0\57\0\u0758\0\u0787\0\u07b6"+
    "\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e"+
    "\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6"+
    "\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e"+
    "\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96"+
    "\0\57\0\u0dc5\0\u0df4\0\u069c\0\u0e23\0\u0e52\0\u0e81\0\u0eb0"+
    "\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\u1028"+
    "\0\u1057\0\u1086\0\u10b5\0\u10e4\0\u1113\0\u1142\0\u1171\0\u11a0"+
    "\0\u11cf\0\u11fe\0\u122d\0\u125c\0\u128b\0\u12ba\0\u12e9\0\u1318"+
    "\0\u1347\0\u1376\0\u13a5\0\u13d4\0\u1403\0\u1432\0\u1461\0\u1490"+
    "\0\u14bf\0\u14ee\0\u151d\0\u154c\0\u157b\0\u15aa\0\u15d9\0\u1608"+
    "\0\u1637\0\u1666\0\u1695\0\u16c4\0\u16f3\0\u01a7\0\u1722\0\u1751"+
    "\0\u1780\0\u17af\0\u17de\0\u180d\0\u183c\0\u186b\0\u189a\0\u01a7"+
    "\0\u18c9\0\u18f8\0\u1927\0\u01a7\0\u1956\0\u1985\0\u19b4\0\u19e3"+
    "\0\u1a12\0\u1a41\0\u1a70\0\u1a9f\0\u1ace\0\u1afd\0\u1b2c\0\u1b5b"+
    "\0\u1b8a\0\u1bb9\0\u1be8\0\u1c17\0\u1c46\0\u1c75\0\u1ca4\0\u1cd3"+
    "\0\u1d02\0\u1d31\0\u1d60\0\u01a7\0\u1d8f\0\u1dbe\0\u1ded\0\u01a7"+
    "\0\u1e1c\0\u1e4b\0\u1e7a\0\u01a7\0\u1ea9\0\u1ed8\0\u1f07\0\u1f36"+
    "\0\u1f65\0\u01a7\0\u1f94\0\u1fc3\0\u01a7\0\u1ff2\0\u2021\0\u2050"+
    "\0\u01a7\0\u01a7\0\u207f\0\u01a7\0\u20ae\0\u20dd\0\u210c\0\u213b"+
    "\0\u216a\0\u2199\0\u21c8\0\u21f7\0\u2226\0\u2255\0\u2284\0\u22b3"+
    "\0\u22e2\0\u01a7\0\u01a7\0\u2311\0\u2340\0\u236f\0\u239e\0\u23cd"+
    "\0\u01a7\0\u01a7\0\u23fc\0\u242b\0\u245a\0\u2489\0\u24b8\0\u24e7"+
    "\0\u2516\0\u2545\0\u2574\0\u01a7\0\u25a3\0\u01a7\0\u25d2\0\u2601"+
    "\0\u2630\0\u265f\0\u268e\0\u26bd\0\u26ec\0\u271b\0\u274a\0\u2779"+
    "\0\u27a8\0\u01a7\0\u27d7\0\u01a7\0\u2806\0\u2835\0\u2864\0\u2893"+
    "\0\u01a7\0\u01a7\0\u01a7\0\u28c2\0\u28f1\0\u01a7\0\u2920\0\u01a7"+
    "\0\57\0\57\0\u294f\0\u297e\0\u29ad\0\u01a7\0\u01a7\0\u01a7"+
    "\0\u29dc\0\u2a0b\0\u2a3a\0\u01a7\0\u2a69\0\u2a98\0\u01a7\0\u2ac7"+
    "\0\u2af6\0\u01a7\0\u01a7\0\u2b25\0\u2b54\0\u2b83\0\u2bb2\0\u2be1"+
    "\0\u2c10\0\u01a7\0\u01a7\0\u2c3f\0\u2c6e\0\u01a7\0\u2c9d\0\u01a7"+
    "\0\u2ccc\0\u2cfb\0\u2d2a\0\u2d59\0\u01a7\0\u01a7\0\u2d88\0\u2db7"+
    "\0\u2de6\0\u01a7\0\u01a7\0\u2e15\0\u01a7\0\u01a7";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[302];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\0\1\11\1\12\1\0\1\13\1\14\1\15"+
    "\2\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\16\1\32\1\33\1\34"+
    "\1\16\1\35\1\36\1\37\1\40\1\41\1\42\4\16"+
    "\1\0\1\43\61\0\1\3\73\0\4\44\2\0\30\44"+
    "\2\0\2\7\1\3\54\7\17\0\1\45\1\15\54\0"+
    "\1\46\4\0\1\47\50\0\1\50\1\0\2\51\1\0"+
    "\1\52\6\0\1\52\42\0\1\50\1\0\2\15\1\0"+
    "\1\52\6\0\1\52\44\0\4\16\2\0\30\16\26\0"+
    "\1\53\51\0\4\54\1\0\1\55\23\54\1\56\4\54"+
    "\21\0\4\16\2\0\1\16\1\57\1\16\1\60\24\16"+
    "\21\0\4\16\2\0\1\61\16\16\1\62\10\16\21\0"+
    "\4\16\2\0\10\16\1\63\3\16\1\64\5\16\1\65"+
    "\5\16\21\0\4\16\2\0\22\16\1\66\5\16\21\0"+
    "\4\16\2\0\11\16\1\67\1\16\1\70\4\16\1\71"+
    "\2\16\1\72\4\16\21\0\4\16\2\0\1\73\7\16"+
    "\1\74\17\16\21\0\4\16\2\0\1\75\16\16\1\76"+
    "\10\16\21\0\4\16\2\0\1\77\7\16\1\100\17\16"+
    "\21\0\4\16\2\0\13\16\1\101\14\16\21\0\4\16"+
    "\2\0\1\102\3\16\1\103\3\16\1\104\17\16\21\0"+
    "\4\16\2\0\1\105\13\16\1\106\13\16\21\0\4\16"+
    "\2\0\15\16\1\107\12\16\21\0\4\16\2\0\22\16"+
    "\1\110\5\16\21\0\4\16\2\0\4\16\1\111\7\16"+
    "\1\112\13\16\21\0\4\16\2\0\10\16\1\113\2\16"+
    "\1\114\14\16\21\0\4\16\2\0\17\16\1\115\10\16"+
    "\21\0\4\16\2\0\15\16\1\116\12\16\21\0\4\16"+
    "\2\0\1\117\27\16\57\0\1\120\10\0\1\121\7\0"+
    "\4\44\2\0\30\44\17\0\1\50\4\0\1\52\6\0"+
    "\1\52\25\0\2\46\4\0\51\46\12\0\1\122\63\0"+
    "\2\123\55\0\2\51\52\0\1\124\2\0\2\51\36\0"+
    "\23\53\1\17\1\125\32\53\17\0\4\54\1\0\1\55"+
    "\30\54\21\0\4\54\1\0\1\55\4\54\1\126\23\54"+
    "\21\0\4\16\2\0\17\16\1\127\10\16\21\0\4\16"+
    "\2\0\23\16\1\130\4\16\21\0\4\16\2\0\11\16"+
    "\1\131\16\16\21\0\4\16\2\0\14\16\1\132\13\16"+
    "\21\0\4\16\2\0\4\16\1\133\23\16\21\0\4\16"+
    "\2\0\17\16\1\134\10\16\21\0\4\16\2\0\15\16"+
    "\1\135\12\16\21\0\4\16\2\0\4\16\1\136\23\16"+
    "\21\0\4\16\2\0\5\16\1\137\22\16\21\0\4\16"+
    "\2\0\21\16\1\140\1\16\1\141\4\16\21\0\4\16"+
    "\2\0\2\16\1\142\25\16\21\0\4\16\2\0\4\16"+
    "\1\143\23\16\21\0\4\16\2\0\11\16\1\144\16\16"+
    "\21\0\4\16\2\0\13\16\1\145\14\16\21\0\4\16"+
    "\2\0\20\16\1\146\7\16\21\0\4\16\2\0\10\16"+
    "\1\147\17\16\21\0\4\16\2\0\3\16\1\150\24\16"+
    "\21\0\4\16\2\0\20\16\1\151\7\16\21\0\4\16"+
    "\2\0\21\16\1\152\6\16\21\0\4\16\2\0\6\16"+
    "\1\153\10\16\1\154\10\16\21\0\4\16\2\0\11\16"+
    "\1\155\16\16\21\0\4\16\2\0\13\16\1\156\14\16"+
    "\21\0\4\16\2\0\17\16\1\157\3\16\1\160\4\16"+
    "\21\0\4\16\2\0\2\16\1\161\25\16\21\0\4\16"+
    "\2\0\4\16\1\162\23\16\21\0\4\16\2\0\10\16"+
    "\1\163\17\16\21\0\4\16\2\0\26\16\1\164\1\16"+
    "\21\0\4\16\2\0\3\16\1\165\24\16\21\0\4\16"+
    "\2\0\6\16\1\166\21\16\21\0\4\16\2\0\14\16"+
    "\1\167\13\16\21\0\4\16\2\0\22\16\1\170\5\16"+
    "\21\0\4\16\2\0\1\171\27\16\21\0\4\16\2\0"+
    "\17\16\1\172\10\16\40\0\1\173\20\0\12\122\1\0"+
    "\10\122\1\174\33\122\17\0\2\123\1\0\1\52\6\0"+
    "\1\52\43\0\1\3\57\0\4\54\1\0\1\55\17\54"+
    "\1\175\10\54\21\0\4\16\2\0\4\16\1\176\23\16"+
    "\21\0\4\16\2\0\10\16\1\177\17\16\21\0\4\16"+
    "\2\0\21\16\1\200\6\16\21\0\4\16\2\0\12\16"+
    "\1\201\15\16\21\0\4\16\2\0\17\16\1\202\10\16"+
    "\21\0\4\16\2\0\21\16\1\203\6\16\21\0\4\16"+
    "\2\0\10\16\1\204\17\16\21\0\4\16\2\0\13\16"+
    "\1\205\14\16\21\0\4\16\2\0\14\16\1\206\13\16"+
    "\21\0\4\16\2\0\17\16\1\207\10\16\21\0\4\16"+
    "\2\0\10\16\1\210\11\16\1\211\5\16\21\0\4\16"+
    "\2\0\22\16\1\212\5\16\21\0\4\16\2\0\17\16"+
    "\1\213\10\16\21\0\4\16\2\0\20\16\1\214\7\16"+
    "\21\0\4\16\2\0\17\16\1\215\10\16\21\0\4\16"+
    "\2\0\15\16\1\216\12\16\21\0\4\16\2\0\13\16"+
    "\1\217\14\16\21\0\4\16\2\0\1\220\27\16\21\0"+
    "\4\16\2\0\21\16\1\221\6\16\21\0\4\16\2\0"+
    "\4\16\1\222\23\16\21\0\4\16\2\0\14\16\1\223"+
    "\13\16\21\0\4\16\2\0\26\16\1\224\1\16\21\0"+
    "\4\16\2\0\2\16\1\225\25\16\21\0\4\16\2\0"+
    "\20\16\1\226\7\16\21\0\4\16\2\0\17\16\1\227"+
    "\10\16\21\0\4\16\2\0\10\16\1\230\17\16\21\0"+
    "\4\16\2\0\7\16\1\231\20\16\21\0\4\16\2\0"+
    "\13\16\1\232\14\16\21\0\4\16\2\0\4\16\1\233"+
    "\23\16\21\0\4\16\2\0\4\16\1\234\23\16\21\0"+
    "\4\16\2\0\14\16\1\235\13\16\21\0\4\16\2\0"+
    "\22\16\1\236\5\16\21\0\4\16\2\0\24\16\1\237"+
    "\3\16\21\0\4\16\2\0\4\16\1\240\23\16\21\0"+
    "\4\16\2\0\21\16\1\241\6\16\21\0\4\16\2\0"+
    "\10\16\1\242\17\16\50\0\1\243\10\0\12\122\1\125"+
    "\10\122\1\174\33\122\17\0\4\54\1\0\1\55\1\244"+
    "\27\54\21\0\4\16\2\0\2\16\1\245\1\16\1\246"+
    "\12\16\1\247\10\16\21\0\4\16\2\0\4\16\1\250"+
    "\23\16\21\0\4\16\2\0\1\251\27\16\21\0\4\16"+
    "\2\0\10\16\1\252\17\16\21\0\4\16\2\0\17\16"+
    "\1\253\10\16\21\0\4\16\2\0\1\254\27\16\21\0"+
    "\4\16\2\0\3\16\1\255\24\16\21\0\4\16\2\0"+
    "\3\16\1\256\24\16\21\0\4\16\2\0\4\16\1\257"+
    "\23\16\21\0\4\16\2\0\1\260\27\16\21\0\4\16"+
    "\2\0\4\16\1\261\23\16\21\0\4\16\2\0\2\16"+
    "\1\262\25\16\21\0\4\16\2\0\6\16\1\263\21\16"+
    "\21\0\4\16\2\0\4\16\1\264\23\16\21\0\4\16"+
    "\2\0\4\16\1\265\23\16\21\0\4\16\2\0\1\266"+
    "\27\16\21\0\4\16\2\0\2\16\1\267\25\16\21\0"+
    "\4\16\2\0\14\16\1\270\13\16\21\0\4\16\2\0"+
    "\17\16\1\271\10\16\21\0\4\16\2\0\20\16\1\272"+
    "\7\16\21\0\4\16\2\0\7\16\1\273\20\16\21\0"+
    "\4\16\2\0\21\16\1\274\6\16\21\0\4\16\2\0"+
    "\1\275\27\16\21\0\4\16\2\0\3\16\1\276\24\16"+
    "\21\0\4\16\2\0\4\16\1\277\23\16\21\0\4\16"+
    "\2\0\20\16\1\300\7\16\21\0\4\16\2\0\13\16"+
    "\1\301\14\16\21\0\4\16\2\0\20\16\1\302\7\16"+
    "\21\0\4\16\2\0\11\16\1\303\16\16\21\0\4\16"+
    "\2\0\4\16\1\304\23\16\21\0\4\16\2\0\1\16"+
    "\1\305\26\16\21\0\4\16\2\0\13\16\1\306\14\16"+
    "\21\0\4\16\2\0\17\16\1\307\10\16\21\0\4\16"+
    "\2\0\14\16\1\310\13\16\37\0\1\311\40\0\4\54"+
    "\1\0\1\55\13\54\1\312\14\54\21\0\4\16\2\0"+
    "\22\16\1\313\5\16\21\0\4\16\2\0\12\16\1\314"+
    "\15\16\21\0\4\16\2\0\4\16\1\315\23\16\21\0"+
    "\4\16\2\0\13\16\1\316\14\16\21\0\4\16\2\0"+
    "\27\16\1\317\21\0\4\16\2\0\20\16\1\320\7\16"+
    "\21\0\4\16\2\0\1\321\27\16\21\0\4\16\2\0"+
    "\14\16\1\322\13\16\21\0\4\16\2\0\4\16\1\323"+
    "\23\16\21\0\4\16\2\0\6\16\1\324\21\16\21\0"+
    "\4\16\2\0\11\16\1\325\16\16\21\0\4\16\2\0"+
    "\7\16\1\326\20\16\21\0\4\16\2\0\17\16\1\327"+
    "\10\16\21\0\4\16\2\0\6\16\1\330\21\16\21\0"+
    "\4\16\2\0\17\16\1\331\10\16\21\0\4\16\2\0"+
    "\7\16\1\332\20\16\21\0\4\16\2\0\17\16\1\333"+
    "\10\16\21\0\4\16\2\0\2\16\1\334\25\16\21\0"+
    "\4\16\2\0\14\16\1\335\13\16\21\0\4\16\2\0"+
    "\10\16\1\336\17\16\21\0\4\16\2\0\1\337\27\16"+
    "\21\0\4\16\2\0\1\16\1\340\26\16\21\0\4\16"+
    "\2\0\11\16\1\341\16\16\21\0\4\16\2\0\5\16"+
    "\1\342\22\16\21\0\4\16\2\0\1\343\27\16\21\0"+
    "\4\16\2\0\14\16\1\344\13\16\21\0\4\16\2\0"+
    "\4\16\1\345\23\16\21\0\4\16\2\0\20\16\1\346"+
    "\7\16\41\0\1\347\36\0\4\54\1\0\1\55\14\54"+
    "\1\350\13\54\21\0\4\16\2\0\4\16\1\351\23\16"+
    "\21\0\4\16\2\0\15\16\1\352\12\16\21\0\4\16"+
    "\2\0\6\16\1\353\21\16\21\0\4\16\2\0\21\16"+
    "\1\354\6\16\21\0\4\16\2\0\1\355\27\16\21\0"+
    "\4\16\2\0\21\16\1\356\6\16\21\0\4\16\2\0"+
    "\2\16\1\357\1\16\1\360\12\16\1\361\10\16\21\0"+
    "\4\16\2\0\1\362\27\16\21\0\4\16\2\0\23\16"+
    "\1\363\4\16\21\0\4\16\2\0\1\364\27\16\21\0"+
    "\4\16\2\0\4\16\1\365\23\16\21\0\4\16\2\0"+
    "\1\366\27\16\21\0\4\16\2\0\10\16\1\367\17\16"+
    "\21\0\4\16\2\0\1\370\27\16\21\0\4\16\2\0"+
    "\17\16\1\371\10\16\21\0\4\16\2\0\25\16\1\372"+
    "\2\16\21\0\4\16\2\0\3\16\1\373\24\16\21\0"+
    "\4\16\2\0\22\16\1\374\5\16\21\0\4\16\2\0"+
    "\1\375\27\16\21\0\4\16\2\0\14\16\1\376\13\16"+
    "\21\0\4\16\2\0\11\16\1\377\16\16\21\0\4\16"+
    "\2\0\4\16\1\u0100\23\16\43\0\1\u0101\34\0\4\54"+
    "\1\0\1\u0102\30\54\21\0\4\16\2\0\13\16\1\u0103"+
    "\14\16\21\0\4\16\2\0\1\u0104\27\16\21\0\4\16"+
    "\2\0\1\u0105\27\16\21\0\4\16\2\0\14\16\1\u0106"+
    "\13\16\21\0\4\16\2\0\17\16\1\u0107\10\16\21\0"+
    "\4\16\2\0\1\u0108\27\16\21\0\4\16\2\0\22\16"+
    "\1\u0109\5\16\21\0\4\16\2\0\12\16\1\u010a\15\16"+
    "\21\0\4\16\2\0\4\16\1\u010b\23\16\21\0\4\16"+
    "\2\0\4\16\1\u010c\23\16\21\0\4\16\2\0\4\16"+
    "\1\u010d\23\16\21\0\4\16\2\0\11\16\1\u010e\16\16"+
    "\21\0\4\16\2\0\1\u010f\27\16\21\0\4\16\2\0"+
    "\12\16\1\u0110\15\16\21\0\4\16\2\0\4\16\1\u0111"+
    "\23\16\21\0\4\16\2\0\4\16\1\u0112\23\16\21\0"+
    "\4\16\2\0\11\16\1\u0113\16\16\21\0\4\16\2\0"+
    "\21\16\1\u0114\6\16\21\0\4\16\2\0\16\16\1\u0115"+
    "\11\16\21\0\4\16\2\0\11\16\1\u0116\16\16\21\0"+
    "\4\16\2\0\4\16\1\u0117\23\16\21\0\4\16\2\0"+
    "\15\16\1\u0118\12\16\21\0\4\16\2\0\6\16\1\u0119"+
    "\21\16\21\0\4\16\2\0\13\16\1\u011a\14\16\21\0"+
    "\4\16\2\0\14\16\1\u011b\13\16\21\0\4\16\2\0"+
    "\1\16\1\u011c\26\16\21\0\4\16\2\0\13\16\1\u011d"+
    "\14\16\21\0\4\16\2\0\14\16\1\u011e\13\16\21\0"+
    "\4\16\2\0\22\16\1\u011f\5\16\21\0\4\16\2\0"+
    "\14\16\1\u0120\13\16\21\0\4\16\2\0\13\16\1\u0121"+
    "\14\16\21\0\4\16\2\0\1\u0122\27\16\21\0\4\16"+
    "\2\0\1\u0123\27\16\21\0\4\16\2\0\10\16\1\u0124"+
    "\17\16\21\0\4\16\2\0\1\u0125\27\16\21\0\4\16"+
    "\2\0\4\16\1\u0126\23\16\21\0\4\16\2\0\21\16"+
    "\1\u0127\6\16\21\0\4\16\2\0\16\16\1\u0128\11\16"+
    "\21\0\4\16\2\0\11\16\1\u0129\16\16\21\0\4\16"+
    "\2\0\14\16\1\u012a\13\16\21\0\4\16\2\0\14\16"+
    "\1\u012b\13\16\21\0\4\16\2\0\22\16\1\u012c\5\16"+
    "\21\0\4\16\2\0\14\16\1\u012d\13\16\21\0\4\16"+
    "\2\0\4\16\1\u012e\23\16\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[11844];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\1\11\1\1\1\11\2\1\2\11\2\0"+
    "\3\1\2\0\22\1\2\0\2\1\2\0\1\1\3\0"+
    "\1\11\1\0\41\1\1\0\1\11\1\0\1\1\3\0"+
    "\44\1\3\0\45\1\2\0\44\1\2\0\34\1\2\0"+
    "\30\1\2\11\54\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[302];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    //string para imprimir los contenidos de los tokens encontrados
    StringBuffer string = new StringBuffer();
    private int errorCount = 0;

    //symbol predefinidos por el ejemplo proporcionado por jflex
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }

    //manejar errores y reportar
    private void handleError(String message) {
        System.err.println("ERROR: " + message + ", línea " + yyline + ", columna " + yycolumn);
        errorCount++;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
          // fall through
          case 52: break;
          case 2:
            { return symbol(sym.CHAR);
            }
          // fall through
          case 53: break;
          case 3:
            { return symbol(sym.COMILLADOBLE);
            }
          // fall through
          case 54: break;
          case 4:
            { return symbol(sym.COMILLA);
            }
          // fall through
          case 55: break;
          case 5:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 56: break;
          case 6:
            { return symbol(sym.NUMERO);
            }
          // fall through
          case 57: break;
          case 7:
            { return symbol(sym.STRING);
            }
          // fall through
          case 58: break;
          case 8:
            { return symbol(sym.IDENTIFICADOR);
            }
          // fall through
          case 59: break;
          case 9:
            { return symbol(sym.IF);
            }
          // fall through
          case 60: break;
          case 10:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 61: break;
          case 11:
            { return symbol(sym.IGUALDAD);
            }
          // fall through
          case 62: break;
          case 12:
            { return symbol(sym.TRUE);
            }
          // fall through
          case 63: break;
          case 13:
            { return symbol(sym.BREAK);
            }
          // fall through
          case 64: break;
          case 14:
            { return symbol(sym.RETURN);
            }
          // fall through
          case 65: break;
          case 15:
            { return symbol(sym.FALSE);
            }
          // fall through
          case 66: break;
          case 16:
            { return symbol(sym.MODULO);
            }
          // fall through
          case 67: break;
          case 17:
            { return symbol(sym.PRINT);
            }
          // fall through
          case 68: break;
          case 18:
            { return symbol(sym.INCREMENTO);
            }
          // fall through
          case 69: break;
          case 19:
            { return symbol(sym.DIVISION);
            }
          // fall through
          case 70: break;
          case 20:
            { return symbol(sym.DOSPUNTOS);
            }
          // fall through
          case 71: break;
          case 21:
            { return symbol(sym.FOR);
            }
          // fall through
          case 72: break;
          case 22:
            { return symbol(sym.DISYUNCION);
            }
          // fall through
          case 73: break;
          case 23:
            { return symbol(sym.DECREMENTO);
            }
          // fall through
          case 74: break;
          case 24:
            { return symbol(sym.BOOL);
            }
          // fall through
          case 75: break;
          case 25:
            { return symbol(sym.SWITCH);
            }
          // fall through
          case 76: break;
          case 26:
            { return symbol(sym.ASIGNACION);
            }
          // fall through
          case 77: break;
          case 27:
            { return symbol(sym.READ);
            }
          // fall through
          case 78: break;
          case 28:
            { return symbol(sym.CONJUNCION);
            }
          // fall through
          case 79: break;
          case 29:
            { return symbol(sym.MAYOR);
            }
          // fall through
          case 80: break;
          case 30:
            { return symbol(sym.SUMA);
            }
          // fall through
          case 81: break;
          case 31:
            { return symbol(sym.INTEGER);
            }
          // fall through
          case 82: break;
          case 32:
            { return symbol(sym.MAYORIGUAL);
            }
          // fall through
          case 83: break;
          case 33:
            { return symbol(sym.DEFAULT);
            }
          // fall through
          case 84: break;
          case 34:
            { return symbol(sym.MAIN);
            }
          // fall through
          case 85: break;
          case 35:
            { return symbol(sym.POTENCIA);
            }
          // fall through
          case 86: break;
          case 36:
            { return symbol(sym.NEGACION);
            }
          // fall through
          case 87: break;
          case 37:
            { return symbol(sym.FLOAT);
            }
          // fall through
          case 88: break;
          case 38:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 89: break;
          case 39:
            { return symbol(sym.CASE);
            }
          // fall through
          case 90: break;
          case 40:
            { return symbol(sym.DIFERENTE);
            }
          // fall through
          case 91: break;
          case 41:
            { return symbol(sym.MENOR);
            }
          // fall through
          case 92: break;
          case 42:
            { return symbol(sym.MENORIGUAL);
            }
          // fall through
          case 93: break;
          case 43:
            { return symbol(sym.ENDEXPR);
            }
          // fall through
          case 94: break;
          case 44:
            { return symbol(sym.BRACEIZQ);
            }
          // fall through
          case 95: break;
          case 45:
            { return symbol(sym.PARENIZQ);
            }
          // fall through
          case 96: break;
          case 46:
            { return symbol(sym.MULTIPLICACION);
            }
          // fall through
          case 97: break;
          case 47:
            { return symbol(sym.CORCHETEIZQ);
            }
          // fall through
          case 98: break;
          case 48:
            { return symbol(sym.RESTA);
            }
          // fall through
          case 99: break;
          case 49:
            { return symbol(sym.BRACEDER);
            }
          // fall through
          case 100: break;
          case 50:
            { return symbol(sym.PARENDER);
            }
          // fall through
          case 101: break;
          case 51:
            { return symbol(sym.CORCHETEDER);
            }
          // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
