
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ParserLexer;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.io.FileWriter;
import java.io.IOException;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\143\000\002\002\004\000\002\003\003\000\002\051" +
    "\002\000\002\002\004\000\002\006\003\000\002\006\004" +
    "\000\002\007\004\000\002\004\006\000\002\004\006\000" +
    "\002\052\002\000\002\004\010\000\002\053\002\000\002" +
    "\004\005\000\002\011\003\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\012\005\000\002\013\003\000\002\013\004\000" +
    "\002\013\003\000\002\014\003\000\002\014\003\000\002" +
    "\014\003\000\002\014\003\000\002\014\003\000\002\014" +
    "\003\000\002\014\003\000\002\014\003\000\002\014\003" +
    "\000\002\014\003\000\002\014\003\000\002\045\007\000" +
    "\002\044\006\000\002\043\005\000\002\035\003\000\002" +
    "\032\005\000\002\032\003\000\002\032\004\000\002\036" +
    "\003\000\002\036\003\000\002\033\005\000\002\033\003" +
    "\000\002\037\003\000\002\037\003\000\002\037\003\000" +
    "\002\037\003\000\002\037\003\000\002\037\003\000\002" +
    "\031\005\000\002\031\003\000\002\041\004\000\002\041" +
    "\004\000\002\042\006\000\002\034\003\000\002\034\003" +
    "\000\002\034\003\000\002\034\003\000\002\034\003\000" +
    "\002\034\003\000\002\034\003\000\002\034\003\000\002" +
    "\034\005\000\002\040\003\000\002\040\003\000\002\040" +
    "\003\000\002\040\003\000\002\040\003\000\002\040\003" +
    "\000\002\024\005\000\002\025\004\000\002\026\007\000" +
    "\002\027\007\000\002\023\003\000\002\023\003\000\002" +
    "\023\003\000\002\023\003\000\002\015\007\000\002\015" +
    "\011\000\002\016\013\000\002\016\013\000\002\017\007" +
    "\000\002\020\012\000\002\021\006\000\002\021\007\000" +
    "\002\022\005\000\002\022\002\000\002\030\007\000\002" +
    "\010\003\000\002\010\002\000\002\005\003\000\002\005" +
    "\005\000\002\046\010\000\002\046\014\000\002\050\003" +
    "\000\002\050\005\000\002\047\011" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\301\000\020\003\uffff\004\uffff\005\uffff\006\uffff\007" +
    "\uffff\010\uffff\011\uffff\001\002\000\004\002\303\001\002" +
    "\000\020\003\016\004\010\005\020\006\011\007\021\010" +
    "\015\011\014\001\002\000\004\002\000\001\002\000\004" +
    "\022\120\001\002\000\010\051\ufff4\052\ufff4\056\ufff4\001" +
    "\002\000\010\051\ufff2\052\ufff2\056\ufff2\001\002\000\022" +
    "\002\ufffe\003\016\004\010\005\020\006\011\007\021\010" +
    "\015\011\014\001\002\000\006\052\025\056\026\001\002" +
    "\000\010\051\uffef\052\uffef\056\uffef\001\002\000\010\051" +
    "\ufff0\052\ufff0\056\ufff0\001\002\000\020\003\ufff6\004\ufff6" +
    "\005\ufff6\006\ufff6\007\ufff6\010\ufff6\011\ufff6\001\002\000" +
    "\024\002\ufffd\003\ufffd\004\ufffd\005\ufffd\006\ufffd\007\ufffd" +
    "\010\ufffd\011\ufffd\022\ufffd\001\002\000\010\051\ufff3\052" +
    "\ufff3\056\ufff3\001\002\000\010\051\ufff1\052\ufff1\056\ufff1" +
    "\001\002\000\020\003\016\004\010\005\020\006\011\007" +
    "\021\010\015\011\014\001\002\000\022\003\016\004\010" +
    "\005\020\006\011\007\021\010\015\011\014\022\ufff5\001" +
    "\002\000\024\002\ufffc\003\ufffc\004\ufffc\005\ufffc\006\ufffc" +
    "\007\ufffc\010\ufffc\011\ufffc\022\ufffc\001\002\000\004\020" +
    "\031\001\002\000\004\020\027\001\002\000\004\021\030" +
    "\001\002\000\004\022\ufffa\001\002\000\022\006\ufff8\007" +
    "\ufff8\010\ufff8\020\ufff8\021\032\040\ufff8\052\ufff8\053\ufff8" +
    "\001\002\000\004\022\ufff9\001\002\000\020\006\035\007" +
    "\052\010\040\020\042\040\050\052\051\053\041\001\002" +
    "\000\006\021\uffa5\060\uffa5\001\002\000\050\012\uffc6\013" +
    "\uffc6\014\uffc6\015\uffc6\016\uffc6\017\uffc6\021\uffc6\025\uffc6" +
    "\030\uffc6\031\uffc6\032\uffc6\033\uffc6\034\uffc6\035\uffc6\036" +
    "\uffc6\037\uffc6\051\uffc6\057\uffc6\060\uffc6\001\002\000\016" +
    "\021\uffda\025\uffda\036\uffda\037\uffda\057\uffda\060\uffda\001" +
    "\002\000\050\012\uffc4\013\uffc4\014\uffc4\015\uffc4\016\uffc4" +
    "\017\uffc4\021\uffc4\025\uffc4\030\uffc4\031\uffc4\032\uffc4\033" +
    "\uffc4\034\uffc4\035\uffc4\036\uffc4\037\uffc4\051\uffc4\057\uffc4" +
    "\060\uffc4\001\002\000\050\012\uffc7\013\uffc7\014\uffc7\015" +
    "\uffc7\016\uffc7\017\uffc7\021\uffc7\025\uffc7\030\uffc7\031\uffc7" +
    "\032\uffc7\033\uffc7\034\uffc7\035\uffc7\036\uffc7\037\uffc7\051" +
    "\uffc7\057\uffc7\060\uffc7\001\002\000\050\012\uffc9\013\uffc9" +
    "\014\uffc9\015\uffc9\016\uffc9\017\uffc9\021\uffc9\025\uffc9\030" +
    "\uffc9\031\uffc9\032\uffc9\033\uffc9\034\uffc9\035\uffc9\036\uffc9" +
    "\037\uffc9\051\uffc9\057\uffc9\060\uffc9\001\002\000\020\006" +
    "\035\007\052\010\040\020\042\040\050\052\051\053\041" +
    "\001\002\000\050\012\uffc5\013\uffc5\014\uffc5\015\uffc5\016" +
    "\uffc5\017\uffc5\021\uffc5\025\uffc5\030\uffc5\031\uffc5\032\uffc5" +
    "\033\uffc5\034\uffc5\035\uffc5\036\uffc5\037\uffc5\051\uffc5\057" +
    "\uffc5\060\uffc5\001\002\000\016\021\uffdc\025\uffdc\036\113" +
    "\037\114\057\uffdc\060\uffdc\001\002\000\046\012\uffcd\013" +
    "\uffcd\014\uffcd\015\uffcd\016\uffcd\017\uffcd\021\uffcd\025\uffcd" +
    "\030\uffcd\031\uffcd\032\uffcd\033\uffcd\034\uffcd\035\uffcd\036" +
    "\uffcd\037\uffcd\057\uffcd\060\uffcd\001\002\000\006\021\111" +
    "\060\064\001\002\000\046\012\075\013\071\014\101\015" +
    "\100\016\073\017\105\021\uffd5\025\uffd5\030\076\031\104" +
    "\032\103\033\077\034\102\035\074\036\uffd5\037\uffd5\057" +
    "\uffd5\060\uffd5\001\002\000\016\006\035\007\052\010\040" +
    "\020\042\052\051\053\041\001\002\000\060\012\uffc2\013" +
    "\uffc2\014\uffc2\015\uffc2\016\uffc2\017\uffc2\020\055\021\uffc2" +
    "\024\056\025\uffc2\026\057\027\054\030\uffc2\031\uffc2\032" +
    "\uffc2\033\uffc2\034\uffc2\035\uffc2\036\uffc2\037\uffc2\051\uffc2" +
    "\057\uffc2\060\uffc2\001\002\000\050\012\uffc8\013\uffc8\014" +
    "\uffc8\015\uffc8\016\uffc8\017\uffc8\021\uffc8\025\uffc8\030\uffc8" +
    "\031\uffc8\032\uffc8\033\uffc8\034\uffc8\035\uffc8\036\uffc8\037" +
    "\uffc8\051\uffc8\057\uffc8\060\uffc8\001\002\000\050\012\uffc3" +
    "\013\uffc3\014\uffc3\015\uffc3\016\uffc3\017\uffc3\021\uffc3\025" +
    "\uffc3\030\uffc3\031\uffc3\032\uffc3\033\uffc3\034\uffc3\035\uffc3" +
    "\036\uffc3\037\uffc3\051\uffc3\057\uffc3\060\uffc3\001\002\000" +
    "\050\012\uffcb\013\uffcb\014\uffcb\015\uffcb\016\uffcb\017\uffcb" +
    "\021\uffcb\025\uffcb\030\uffcb\031\uffcb\032\uffcb\033\uffcb\034" +
    "\uffcb\035\uffcb\036\uffcb\037\uffcb\051\uffcb\057\uffcb\060\uffcb" +
    "\001\002\000\022\006\035\007\052\010\040\020\042\021" +
    "\uffa6\040\050\052\051\053\041\001\002\000\020\006\035" +
    "\007\052\010\040\020\042\040\050\052\051\053\041\001" +
    "\002\000\050\012\uffcc\013\uffcc\014\uffcc\015\uffcc\016\uffcc" +
    "\017\uffcc\021\uffcc\025\uffcc\030\uffcc\031\uffcc\032\uffcc\033" +
    "\uffcc\034\uffcc\035\uffcc\036\uffcc\037\uffcc\051\uffcc\057\uffcc" +
    "\060\uffcc\001\002\000\004\025\061\001\002\000\050\012" +
    "\uffca\013\uffca\014\uffca\015\uffca\016\uffca\017\uffca\021\uffca" +
    "\025\uffca\030\uffca\031\uffca\032\uffca\033\uffca\034\uffca\035" +
    "\uffca\036\uffca\037\uffca\051\uffca\057\uffca\060\uffca\001\002" +
    "\000\004\021\066\001\002\000\006\021\uffa7\060\064\001" +
    "\002\000\020\006\035\007\052\010\040\020\042\040\050" +
    "\052\051\053\041\001\002\000\006\021\uffa4\060\uffa4\001" +
    "\002\000\004\057\067\001\002\000\110\004\uffa8\005\uffa8" +
    "\006\uffa8\007\uffa8\010\uffa8\011\uffa8\012\uffa8\013\uffa8\014" +
    "\uffa8\015\uffa8\016\uffa8\017\uffa8\021\uffa8\023\uffa8\025\uffa8" +
    "\030\uffa8\031\uffa8\032\uffa8\033\uffa8\034\uffa8\035\uffa8\036" +
    "\uffa8\037\uffa8\041\uffa8\043\uffa8\044\uffa8\045\uffa8\047\uffa8" +
    "\050\uffa8\051\uffa8\052\uffa8\057\uffa8\060\uffa8\063\uffa8\064" +
    "\uffa8\001\002\000\016\021\uffd9\025\uffd9\036\uffd9\037\uffd9" +
    "\057\uffd9\060\uffd9\001\002\000\016\006\uffd2\007\uffd2\010" +
    "\uffd2\020\uffd2\052\uffd2\053\uffd2\001\002\000\016\006\035" +
    "\007\052\010\040\020\042\052\051\053\041\001\002\000" +
    "\016\006\uffd0\007\uffd0\010\uffd0\020\uffd0\052\uffd0\053\uffd0" +
    "\001\002\000\016\006\uffbb\007\uffbb\010\uffbb\020\uffbb\052" +
    "\uffbb\053\uffbb\001\002\000\016\006\uffd3\007\uffd3\010\uffd3" +
    "\020\uffd3\052\uffd3\053\uffd3\001\002\000\016\006\uffc0\007" +
    "\uffc0\010\uffc0\020\uffc0\052\uffc0\053\uffc0\001\002\000\016" +
    "\006\uffbd\007\uffbd\010\uffbd\020\uffbd\052\uffbd\053\uffbd\001" +
    "\002\000\016\006\uffd1\007\uffd1\010\uffd1\020\uffd1\052\uffd1" +
    "\053\uffd1\001\002\000\016\006\uffd4\007\uffd4\010\uffd4\020" +
    "\uffd4\052\uffd4\053\uffd4\001\002\000\016\006\uffbc\007\uffbc" +
    "\010\uffbc\020\uffbc\052\uffbc\053\uffbc\001\002\000\016\006" +
    "\uffbe\007\uffbe\010\uffbe\020\uffbe\052\uffbe\053\uffbe\001\002" +
    "\000\016\006\uffbf\007\uffbf\010\uffbf\020\uffbf\052\uffbf\053" +
    "\uffbf\001\002\000\016\006\uffcf\007\uffcf\010\uffcf\020\uffcf" +
    "\052\uffcf\053\uffcf\001\002\000\016\006\035\007\052\010" +
    "\040\020\042\052\051\053\041\001\002\000\032\021\uffd6" +
    "\025\uffd6\030\076\031\104\032\103\033\077\034\102\035" +
    "\074\036\uffd6\037\uffd6\057\uffd6\060\uffd6\001\002\000\046" +
    "\012\uffce\013\uffce\014\uffce\015\uffce\016\uffce\017\uffce\021" +
    "\uffce\025\uffce\030\uffce\031\uffce\032\uffce\033\uffce\034\uffce" +
    "\035\uffce\036\uffce\037\uffce\057\uffce\060\uffce\001\002\000" +
    "\004\022\ufff7\001\002\000\016\006\035\007\052\010\040" +
    "\020\042\052\051\053\041\001\002\000\016\006\uffd7\007" +
    "\uffd7\010\uffd7\020\uffd7\052\uffd7\053\uffd7\001\002\000\016" +
    "\006\uffd8\007\uffd8\010\uffd8\020\uffd8\052\uffd8\053\uffd8\001" +
    "\002\000\016\021\uffdb\025\uffdb\036\uffdb\037\uffdb\057\uffdb" +
    "\060\uffdb\001\002\000\004\021\117\001\002\000\050\012" +
    "\uffc1\013\uffc1\014\uffc1\015\uffc1\016\uffc1\017\uffc1\021\uffc1" +
    "\025\uffc1\030\uffc1\031\uffc1\032\uffc1\033\uffc1\034\uffc1\035" +
    "\uffc1\036\uffc1\037\uffc1\051\uffc1\057\uffc1\060\uffc1\001\002" +
    "\000\042\003\145\004\010\005\020\006\011\007\021\010" +
    "\015\011\014\041\133\043\155\044\127\045\132\047\143" +
    "\050\131\052\150\063\146\064\123\001\002\000\024\002" +
    "\ufffb\003\ufffb\004\ufffb\005\ufffb\006\ufffb\007\ufffb\010\ufffb" +
    "\011\ufffb\022\ufffb\001\002\000\042\004\uffe0\005\uffe0\006" +
    "\uffe0\007\uffe0\010\uffe0\011\uffe0\023\uffe0\041\uffe0\043\uffe0" +
    "\044\uffe0\045\uffe0\047\uffe0\050\uffe0\052\uffe0\063\uffe0\064" +
    "\uffe0\001\002\000\004\020\277\001\002\000\042\004\uffe8" +
    "\005\uffe8\006\uffe8\007\uffe8\010\uffe8\011\uffe8\023\uffe8\041" +
    "\uffe8\043\uffe8\044\uffe8\045\uffe8\047\uffe8\050\uffe8\052\uffe8" +
    "\063\uffe8\064\uffe8\001\002\000\042\004\010\005\020\006" +
    "\011\007\021\010\015\011\014\023\276\041\133\043\155" +
    "\044\127\045\132\047\143\050\131\052\150\063\146\064" +
    "\123\001\002\000\042\004\uffe6\005\uffe6\006\uffe6\007\uffe6" +
    "\010\uffe6\011\uffe6\023\uffe6\041\uffe6\043\uffe6\044\uffe6\045" +
    "\uffe6\047\uffe6\050\uffe6\052\uffe6\063\uffe6\064\uffe6\001\002" +
    "\000\004\020\271\001\002\000\042\004\uffe2\005\uffe2\006" +
    "\uffe2\007\uffe2\010\uffe2\011\uffe2\023\uffe2\041\uffe2\043\uffe2" +
    "\044\uffe2\045\uffe2\047\uffe2\050\uffe2\052\uffe2\063\uffe2\064" +
    "\uffe2\001\002\000\020\006\035\007\052\010\040\020\042" +
    "\040\050\052\051\053\041\001\002\000\004\020\245\001" +
    "\002\000\004\020\237\001\002\000\042\004\uffe9\005\uffe9" +
    "\006\uffe9\007\uffe9\010\uffe9\011\uffe9\023\uffe9\041\uffe9\043" +
    "\uffe9\044\uffe9\045\uffe9\047\uffe9\050\uffe9\052\uffe9\063\uffe9" +
    "\064\uffe9\001\002\000\042\004\uffb6\005\uffb6\006\uffb6\007" +
    "\uffb6\010\uffb6\011\uffb6\023\uffb6\041\uffb6\043\uffb6\044\uffb6" +
    "\045\uffb6\047\uffb6\050\uffb6\052\uffb6\063\uffb6\064\uffb6\001" +
    "\002\000\004\052\221\001\002\000\042\004\uffed\005\uffed" +
    "\006\uffed\007\uffed\010\uffed\011\uffed\023\uffed\041\uffed\043" +
    "\uffed\044\uffed\045\uffed\047\uffed\050\uffed\052\uffed\063\uffed" +
    "\064\uffed\001\002\000\042\004\uffb3\005\uffb3\006\uffb3\007" +
    "\uffb3\010\uffb3\011\uffb3\023\uffb3\041\uffb3\043\uffb3\044\uffb3" +
    "\045\uffb3\047\uffb3\050\uffb3\052\uffb3\063\uffb3\064\uffb3\001" +
    "\002\000\042\004\uffea\005\uffea\006\uffea\007\uffea\010\uffea" +
    "\011\uffea\023\uffea\041\uffea\043\uffea\044\uffea\045\uffea\047" +
    "\uffea\050\uffea\052\uffea\063\uffea\064\uffea\001\002\000\042" +
    "\004\uffe7\005\uffe7\006\uffe7\007\uffe7\010\uffe7\011\uffe7\023" +
    "\uffe7\041\uffe7\043\uffe7\044\uffe7\045\uffe7\047\uffe7\050\uffe7" +
    "\052\uffe7\063\uffe7\064\uffe7\001\002\000\004\057\220\001" +
    "\002\000\042\004\uffe4\005\uffe4\006\uffe4\007\uffe4\010\uffe4" +
    "\011\uffe4\023\uffe4\041\uffe4\043\uffe4\044\uffe4\045\uffe4\047" +
    "\uffe4\050\uffe4\052\uffe4\063\uffe4\064\uffe4\001\002\000\042" +
    "\004\uffeb\005\uffeb\006\uffeb\007\uffeb\010\uffeb\011\uffeb\023" +
    "\uffeb\041\uffeb\043\uffeb\044\uffeb\045\uffeb\047\uffeb\050\uffeb" +
    "\052\uffeb\063\uffeb\064\uffeb\001\002\000\004\020\214\001" +
    "\002\000\042\004\uffb5\005\uffb5\006\uffb5\007\uffb5\010\uffb5" +
    "\011\uffb5\023\uffb5\041\uffb5\043\uffb5\044\uffb5\045\uffb5\047" +
    "\uffb5\050\uffb5\052\uffb5\063\uffb5\064\uffb5\001\002\000\010" +
    "\020\055\024\206\055\163\001\002\000\042\004\uffe5\005" +
    "\uffe5\006\uffe5\007\uffe5\010\uffe5\011\uffe5\023\uffe5\041\uffe5" +
    "\043\uffe5\044\uffe5\045\uffe5\047\uffe5\050\uffe5\052\uffe5\063" +
    "\uffe5\064\uffe5\001\002\000\042\004\uffb4\005\uffb4\006\uffb4" +
    "\007\uffb4\010\uffb4\011\uffb4\023\uffb4\041\uffb4\043\uffb4\044" +
    "\uffb4\045\uffb4\047\uffb4\050\uffb4\052\uffb4\063\uffb4\064\uffb4" +
    "\001\002\000\042\004\uffe3\005\uffe3\006\uffe3\007\uffe3\010" +
    "\uffe3\011\uffe3\023\uffe3\041\uffe3\043\uffe3\044\uffe3\045\uffe3" +
    "\047\uffe3\050\uffe3\052\uffe3\063\uffe3\064\uffe3\001\002\000" +
    "\042\004\uffe1\005\uffe1\006\uffe1\007\uffe1\010\uffe1\011\uffe1" +
    "\023\uffe1\041\uffe1\043\uffe1\044\uffe1\045\uffe1\047\uffe1\050" +
    "\uffe1\052\uffe1\063\uffe1\064\uffe1\001\002\000\004\020\156" +
    "\001\002\000\020\004\010\005\020\006\011\007\021\010" +
    "\015\011\014\052\162\001\002\000\004\052\202\001\002" +
    "\000\004\057\174\001\002\000\004\057\166\001\002\000" +
    "\004\055\163\001\002\000\020\006\035\007\052\010\040" +
    "\020\042\040\050\052\051\053\041\001\002\000\004\057" +
    "\165\001\002\000\044\004\uffde\005\uffde\006\uffde\007\uffde" +
    "\010\uffde\011\uffde\023\uffde\041\uffde\043\uffde\044\uffde\045" +
    "\uffde\047\uffde\050\uffde\052\uffde\057\uffde\063\uffde\064\uffde" +
    "\001\002\000\020\006\035\007\052\010\040\020\042\040" +
    "\050\052\051\053\041\001\002\000\004\057\170\001\002" +
    "\000\020\006\035\007\052\010\040\020\042\040\050\052" +
    "\051\053\041\001\002\000\004\021\172\001\002\000\004" +
    "\022\120\001\002\000\042\004\uffb0\005\uffb0\006\uffb0\007" +
    "\uffb0\010\uffb0\011\uffb0\023\uffb0\041\uffb0\043\uffb0\044\uffb0" +
    "\045\uffb0\047\uffb0\050\uffb0\052\uffb0\063\uffb0\064\uffb0\001" +
    "\002\000\020\006\035\007\052\010\040\020\042\040\050" +
    "\052\051\053\041\001\002\000\004\057\176\001\002\000" +
    "\020\006\035\007\052\010\040\020\042\040\050\052\051" +
    "\053\041\001\002\000\004\021\200\001\002\000\004\022" +
    "\120\001\002\000\042\004\uffaf\005\uffaf\006\uffaf\007\uffaf" +
    "\010\uffaf\011\uffaf\023\uffaf\041\uffaf\043\uffaf\044\uffaf\045" +
    "\uffaf\047\uffaf\050\uffaf\052\uffaf\063\uffaf\064\uffaf\001\002" +
    "\000\004\055\203\001\002\000\020\006\035\007\052\010" +
    "\040\020\042\040\050\052\051\053\041\001\002\000\004" +
    "\057\205\001\002\000\044\004\uffdf\005\uffdf\006\uffdf\007" +
    "\uffdf\010\uffdf\011\uffdf\023\uffdf\041\uffdf\043\uffdf\044\uffdf" +
    "\045\uffdf\047\uffdf\050\uffdf\052\uffdf\057\uffdf\063\uffdf\064" +
    "\uffdf\001\002\000\020\006\035\007\052\010\040\020\042" +
    "\040\050\052\051\053\041\001\002\000\004\025\210\001" +
    "\002\000\004\055\211\001\002\000\020\006\035\007\052" +
    "\010\040\020\042\040\050\052\051\053\041\001\002\000" +
    "\004\057\213\001\002\000\042\004\uff9f\005\uff9f\006\uff9f" +
    "\007\uff9f\010\uff9f\011\uff9f\023\uff9f\041\uff9f\043\uff9f\044" +
    "\uff9f\045\uff9f\047\uff9f\050\uff9f\052\uff9f\063\uff9f\064\uff9f" +
    "\001\002\000\020\006\035\007\052\010\040\020\042\040" +
    "\050\052\051\053\041\001\002\000\004\021\216\001\002" +
    "\000\004\057\217\001\002\000\042\004\uffb8\005\uffb8\006" +
    "\uffb8\007\uffb8\010\uffb8\011\uffb8\023\uffb8\041\uffb8\043\uffb8" +
    "\044\uffb8\045\uffb8\047\uffb8\050\uffb8\052\uffb8\063\uffb8\064" +
    "\uffb8\001\002\000\042\004\uffb9\005\uffb9\006\uffb9\007\uffb9" +
    "\010\uffb9\011\uffb9\023\uffb9\041\uffb9\043\uffb9\044\uffb9\045" +
    "\uffb9\047\uffb9\050\uffb9\052\uffb9\063\uffb9\064\uffb9\001\002" +
    "\000\010\024\223\055\203\057\222\001\002\000\042\004" +
    "\uffdd\005\uffdd\006\uffdd\007\uffdd\010\uffdd\011\uffdd\023\uffdd" +
    "\041\uffdd\043\uffdd\044\uffdd\045\uffdd\047\uffdd\050\uffdd\052" +
    "\uffdd\063\uffdd\064\uffdd\001\002\000\004\053\224\001\002" +
    "\000\004\025\225\001\002\000\006\055\227\057\226\001" +
    "\002\000\042\004\uffa3\005\uffa3\006\uffa3\007\uffa3\010\uffa3" +
    "\011\uffa3\023\uffa3\041\uffa3\043\uffa3\044\uffa3\045\uffa3\047" +
    "\uffa3\050\uffa3\052\uffa3\063\uffa3\064\uffa3\001\002\000\004" +
    "\024\230\001\002\000\020\006\035\007\052\010\040\020" +
    "\042\040\050\052\051\053\041\001\002\000\006\025\uffa1" +
    "\060\uffa1\001\002\000\006\025\234\060\233\001\002\000" +
    "\020\006\035\007\052\010\040\020\042\040\050\052\051" +
    "\053\041\001\002\000\004\057\235\001\002\000\042\004" +
    "\uffa2\005\uffa2\006\uffa2\007\uffa2\010\uffa2\011\uffa2\023\uffa2" +
    "\041\uffa2\043\uffa2\044\uffa2\045\uffa2\047\uffa2\050\uffa2\052" +
    "\uffa2\063\uffa2\064\uffa2\001\002\000\006\025\uffa0\060\uffa0" +
    "\001\002\000\020\006\035\007\052\010\040\020\042\040" +
    "\050\052\051\053\041\001\002\000\004\021\241\001\002" +
    "\000\004\022\120\001\002\000\044\004\uffb2\005\uffb2\006" +
    "\uffb2\007\uffb2\010\uffb2\011\uffb2\023\uffb2\041\uffb2\042\243" +
    "\043\uffb2\044\uffb2\045\uffb2\047\uffb2\050\uffb2\052\uffb2\063" +
    "\uffb2\064\uffb2\001\002\000\004\022\120\001\002\000\042" +
    "\004\uffb1\005\uffb1\006\uffb1\007\uffb1\010\uffb1\011\uffb1\023" +
    "\uffb1\041\uffb1\043\uffb1\044\uffb1\045\uffb1\047\uffb1\050\uffb1" +
    "\052\uffb1\063\uffb1\064\uffb1\001\002\000\020\006\035\007" +
    "\052\010\040\020\042\040\050\052\051\053\041\001\002" +
    "\000\004\021\247\001\002\000\004\022\250\001\002\000" +
    "\004\046\252\001\002\000\010\023\uffa9\046\260\071\256" +
    "\001\002\000\016\006\035\007\052\010\040\020\042\052" +
    "\051\053\041\001\002\000\004\051\254\001\002\000\004" +
    "\022\120\001\002\000\010\023\uffac\046\uffac\071\uffac\001" +
    "\002\000\004\051\265\001\002\000\004\023\264\001\002" +
    "\000\016\004\010\005\020\006\011\007\021\010\015\011" +
    "\014\001\002\000\004\051\262\001\002\000\004\022\120" +
    "\001\002\000\010\023\uffab\046\uffab\071\uffab\001\002\000" +
    "\042\004\uffad\005\uffad\006\uffad\007\uffad\010\uffad\011\uffad" +
    "\023\uffad\041\uffad\043\uffad\044\uffad\045\uffad\047\uffad\050" +
    "\uffad\052\uffad\063\uffad\064\uffad\001\002\000\004\022\120" +
    "\001\002\000\004\023\uffaa\001\002\000\004\057\270\001" +
    "\002\000\042\004\uffba\005\uffba\006\uffba\007\uffba\010\uffba" +
    "\011\uffba\023\uffba\041\uffba\043\uffba\044\uffba\045\uffba\047" +
    "\uffba\050\uffba\052\uffba\063\uffba\064\uffba\001\002\000\020" +
    "\006\035\007\052\010\040\020\042\040\050\052\051\053" +
    "\041\001\002\000\004\021\273\001\002\000\004\022\120" +
    "\001\002\000\042\004\uffae\005\uffae\006\uffae\007\uffae\010" +
    "\uffae\011\uffae\023\uffae\041\uffae\043\uffae\044\uffae\045\uffae" +
    "\047\uffae\050\uffae\052\uffae\063\uffae\064\uffae\001\002\000" +
    "\042\004\uffec\005\uffec\006\uffec\007\uffec\010\uffec\011\uffec" +
    "\023\uffec\041\uffec\043\uffec\044\uffec\045\uffec\047\uffec\050" +
    "\uffec\052\uffec\063\uffec\064\uffec\001\002\000\056\002\uffee" +
    "\003\uffee\004\uffee\005\uffee\006\uffee\007\uffee\010\uffee\011" +
    "\uffee\022\uffee\023\uffee\041\uffee\042\uffee\043\uffee\044\uffee" +
    "\045\uffee\046\uffee\047\uffee\050\uffee\052\uffee\063\uffee\064" +
    "\uffee\071\uffee\001\002\000\004\052\300\001\002\000\004" +
    "\021\301\001\002\000\004\057\302\001\002\000\042\004" +
    "\uffb7\005\uffb7\006\uffb7\007\uffb7\010\uffb7\011\uffb7\023\uffb7" +
    "\041\uffb7\043\uffb7\044\uffb7\045\uffb7\047\uffb7\050\uffb7\052" +
    "\uffb7\063\uffb7\064\uffb7\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\301\000\010\002\005\003\003\051\004\001\001\000" +
    "\002\001\001\000\012\004\006\006\011\007\016\011\012" +
    "\001\001\000\002\001\001\000\004\012\120\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\004\006\007\023" +
    "\011\012\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\053\021\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\004\006\006" +
    "\022\007\016\011\012\001\001\000\010\004\006\007\023" +
    "\011\012\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\052\032\001\001\000\002\001\001\000\024\005\045\030" +
    "\042\031\046\032\043\033\035\034\044\035\033\041\036" +
    "\042\052\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\030\042\031\046\032\043\033\035\034" +
    "\044\035\115\041\036\042\052\001\001\000\002\001\001" +
    "\000\004\036\111\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\037\105\040\071\001\001\000\016\030\042" +
    "\031\046\033\067\034\044\041\036\042\052\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\026\005\062\010\061\030\042\031\046\032" +
    "\043\033\035\034\044\035\033\041\036\042\052\001\001" +
    "\000\022\030\042\031\046\032\043\033\035\034\044\035" +
    "\057\041\036\042\052\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\030\042\031\046\032\043\033\035\034\044" +
    "\035\064\041\036\042\052\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\030\042\034\107\041\036\042\052\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\030\042\031\106\034" +
    "\044\041\036\042\052\001\001\000\004\040\071\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\030\042\031" +
    "\046\033\114\034\044\041\036\042\052\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\046\011\135\013\124\014\136" +
    "\015\134\016\146\017\151\020\137\023\141\024\125\025" +
    "\150\026\143\027\152\030\127\043\140\044\133\045\123" +
    "\046\121\047\153\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\044\011\135" +
    "\014\274\015\134\016\146\017\151\020\137\023\141\024" +
    "\125\025\150\026\143\027\152\030\127\043\140\044\133" +
    "\045\123\046\121\047\153\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\030\042\031\046" +
    "\032\043\033\035\034\044\035\266\041\036\042\052\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\011\156\044\160\045\157\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\030\042\031\046\032\043\033\035" +
    "\034\044\035\163\041\036\042\052\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\030\042\031\046\032\043" +
    "\033\035\034\044\035\166\041\036\042\052\001\001\000" +
    "\002\001\001\000\022\030\042\031\046\032\043\033\035" +
    "\034\044\035\170\041\036\042\052\001\001\000\002\001" +
    "\001\000\004\012\172\001\001\000\002\001\001\000\022" +
    "\030\042\031\046\032\043\033\035\034\044\035\174\041" +
    "\036\042\052\001\001\000\002\001\001\000\022\030\042" +
    "\031\046\032\043\033\035\034\044\035\176\041\036\042" +
    "\052\001\001\000\002\001\001\000\004\012\200\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\030\042\031" +
    "\046\032\043\033\035\034\044\035\203\041\036\042\052" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\030" +
    "\042\031\046\032\043\033\035\034\044\035\206\041\036" +
    "\042\052\001\001\000\002\001\001\000\002\001\001\000" +
    "\022\030\042\031\046\032\043\033\035\034\044\035\211" +
    "\041\036\042\052\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\030\042\031\046\032\043\033\035\034\044" +
    "\035\214\041\036\042\052\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\024\030\042\031\046\032\043\033\035\034\044\035" +
    "\230\041\036\042\052\050\231\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\030\042\031\046\032\043\033" +
    "\035\034\044\035\235\041\036\042\052\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\030" +
    "\042\031\046\032\043\033\035\034\044\035\237\041\036" +
    "\042\052\001\001\000\002\001\001\000\004\012\241\001" +
    "\001\000\002\001\001\000\004\012\243\001\001\000\002" +
    "\001\001\000\022\030\042\031\046\032\043\033\035\034" +
    "\044\035\245\041\036\042\052\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\021\250\001\001\000\004\022" +
    "\256\001\001\000\012\030\042\034\252\041\036\042\052" +
    "\001\001\000\002\001\001\000\004\012\254\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\260\001\001\000\002\001\001\000\004\012\262\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\012\265" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\030\042\031\046\032\043\033\035\034\044" +
    "\035\271\041\036\042\052\001\001\000\002\001\001\000" +
    "\004\012\273\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 
    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return lex.next_token(); 
    }


    Lexer lex;

    boolean syntaxErrorPrograma = false;
    @SuppressWarnings("deprecation")
    public parser(Lexer lex){
        this.lex = lex;
        this.symbolFactory = new DefaultSymbolFactory();
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {


    HashMap<String, ArrayList<String>> listaTablasSimbolos = new HashMap<String, ArrayList<String>>();
    String currentHash;

    public void imprimirTablaSimbolos(){
        for (String key : listaTablasSimbolos.keySet()) {
            System.out.println("Tabla de simbolos: " + key);
            System.out.println("Valores: ");
            for (String item : listaTablasSimbolos.get(key)) {
                System.out.println(item);
            }
            System.out.println("");
        }
    }

    //escribir en archivo la tabla de simbolos
    public void escribirTablaSimbolos(String nombreArchivo){
        try {
            FileWriter myWriter = new FileWriter(nombreArchivo);
            for (String key : listaTablasSimbolos.keySet()) {
                myWriter.write("Tabla de simbolos: " + key + "\n");
                myWriter.write("Valores: \n");
                for (String item : listaTablasSimbolos.get(key)) {
                    myWriter.write(item + ", ");
                }
                myWriter.write("\n");
            }
            myWriter.close();
            System.out.println("Tabla de simbolos guardada en " + nombreArchivo);
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= _verano_ EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // _verano_ ::= funcion 
            {
              Object RESULT =null;
		 
        imprimirTablaSimbolos();
        escribirTablaSimbolos("tablaSimbolos.txt");
        System.out.println("---Fin---");
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("_verano_",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // NT$0 ::= 
            {
              Object RESULT =null;
System.out.println("\nInicio");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // funcion ::= NT$0 funcionRecur 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // funcionRecur ::= funcion_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcionRecur",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // funcionRecur ::= funcionRecur funcion_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcionRecur",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // funcion_produ ::= funciones_produ bloque_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion_produ",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // funciones_produ ::= tipos MAIN PARENIZQ PARENDER 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		//Funcion main
        ArrayList<String> listaDatos = new ArrayList<String>();
        currentHash = "main";
        String nombre_func = "\nnombre: _verano_";
        String tipo_dato = "tipo: " + t.toString();
        String ambito = "ambito: Funcion Main\n";
        listaDatos.add(nombre_func);
        listaDatos.add(tipo_dato);
        listaDatos.add(ambito);
        listaTablasSimbolos.put(currentHash, listaDatos);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("funciones_produ",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // funciones_produ ::= tipos IDENTIFICADOR PARENIZQ PARENDER 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int iddleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iddright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object idd = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		//Funcion sin parametros
        ArrayList<String> listaDatos = new ArrayList<String>();
        currentHash = "funcion " + idd.toString();
        String nombre_func = "\nnombre: " + idd.toString();
        String tipo_dato = "tipo: " + t.toString();
        String ambito = "ambito: Funcion\n";
        listaDatos.add(nombre_func);
        listaDatos.add(tipo_dato);
        listaDatos.add(ambito);
        listaTablasSimbolos.put(currentHash, listaDatos);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("funciones_produ",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$1 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int iddleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iddright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object idd = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
//tipo
        ArrayList<String> listaDatos = new ArrayList<String>();
        currentHash = "funcion " + idd.toString();
        String nombre_func = "\nnombre: " + idd.toString();
        String tipo_dato = "tipo: " + t.toString();
        String ambito = "ambito: Funcion\n";
        listaDatos.add(nombre_func);
        listaDatos.add(tipo_dato);
        listaDatos.add(ambito);
        listaTablasSimbolos.put(currentHash, listaDatos);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",40, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // funciones_produ ::= tipos IDENTIFICADOR PARENIZQ NT$1 parametros PARENDER 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int iddleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int iddright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object idd = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funciones_produ",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$2 ::= 
            {
              Object RESULT =null;
System.out.println("Error: encabezado no coincide con la gramatica. Buscando el '}' final para salir de esta funcion");
        Symbol token;
        do {
            token = lex.next_token(); //este metodo ya lo trae el lexer
            if (token.sym == sym.BRACEDER || token.sym == sym.EOF) { //busca el } final
                System.out.println("Encontrado el } final");
                break; 
            }
        } while (token != null);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",41, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // funciones_produ ::= error NT$2 funcionRecur 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funciones_produ",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // tipos ::= INTEGER 
            {
              Object RESULT =null;
		RESULT = "int";
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // tipos ::= FLOAT 
            {
              Object RESULT =null;
		RESULT = "float";
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // tipos ::= BOOL 
            {
              Object RESULT =null;
		RESULT = "bool";
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // tipos ::= CHAR 
            {
              Object RESULT =null;
		RESULT = "char";
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipos ::= STRING 
            {
              Object RESULT =null;
		RESULT = "string";
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipos ::= VOID 
            {
              Object RESULT =null;
		RESULT = "void";
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // bloque_produ ::= BRACEIZQ sentencias BRACEDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque_produ",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencias",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencias ::= sentencias sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencias",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentencias ::= error 
            {
              Object RESULT =null;
		
                    System.out.println("Error: falta el token de fin de sentencia (;). Recuperando...");

                    Symbol token;
                    do {
                        token = lex.next_token(); //este metodo ya lo trae el lexer
                        if (token.sym == sym.ENDEXPR || token.sym == sym.EOF) {
                            break; 
                        }
                    } while (token != null); 

                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencias",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia ::= creacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // sentencia ::= asignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // sentencia ::= creacionasignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sentencia ::= estructurasControl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia ::= return_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia ::= break_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia ::= print_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentencia ::= read_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentencia ::= llamadaFuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sentencia ::= modificacionArreglo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // sentencia ::= creacionArreglo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // creacionasignacion ::= tipos IDENTIFICADOR ASIGNACION exprPrin ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("creacionasignacion",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // asignacion ::= IDENTIFICADOR ASIGNACION exprPrin ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("asignacion",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // creacion ::= tipos IDENTIFICADOR ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("creacion",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // exprPrin ::= exprLog 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprPrin",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // exprLog ::= exprLog operadorLog exprRel 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprLog",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // exprLog ::= exprRel 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprLog",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // exprLog ::= NEGACION exprRel 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprLog",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // operadorLog ::= DISYUNCION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorLog",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // operadorLog ::= CONJUNCION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorLog",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // exprRel ::= exprArit operadorRel exprArit 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprRel",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // exprRel ::= exprArit 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprRel",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // operadorRel ::= MAYOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorRel",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // operadorRel ::= MENOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorRel",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // operadorRel ::= MENORIGUAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorRel",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // operadorRel ::= MAYORIGUAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorRel",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // operadorRel ::= IGUALDAD 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorRel",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // operadorRel ::= DIFERENTE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorRel",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // exprArit ::= exprArit operadorArit factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprArit",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // exprArit ::= factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprArit",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // operandoUnario ::= IDENTIFICADOR INCREMENTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operandoUnario",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // operandoUnario ::= IDENTIFICADOR DECREMENTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operandoUnario",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // accesoArreglo ::= IDENTIFICADOR CORCHETEIZQ exprPrin CORCHETEDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accesoArreglo",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // factor ::= NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // factor ::= CHAR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // factor ::= STRING 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // factor ::= BOOL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // factor ::= llamadaFuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // factor ::= operandoUnario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // factor ::= accesoArreglo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // factor ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // factor ::= PARENIZQ exprPrin PARENDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // operadorArit ::= SUMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorArit",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // operadorArit ::= RESTA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorArit",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // operadorArit ::= DIVISION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorArit",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // operadorArit ::= MULTIPLICACION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorArit",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // operadorArit ::= MODULO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorArit",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // operadorArit ::= POTENCIA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operadorArit",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // return_produ ::= RETURN exprPrin ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("return_produ",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // break_produ ::= BREAK ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("break_produ",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // print_produ ::= PRINT PARENIZQ exprPrin PARENDER ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("print_produ",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // read_produ ::= READ PARENIZQ IDENTIFICADOR PARENDER ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("read_produ",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // estructurasControl ::= if_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("estructurasControl",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // estructurasControl ::= for_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("estructurasControl",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // estructurasControl ::= while_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("estructurasControl",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // estructurasControl ::= switch_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("estructurasControl",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // if_produ ::= IF PARENIZQ exprPrin PARENDER bloque_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_produ",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // if_produ ::= IF PARENIZQ exprPrin PARENDER bloque_produ ELSE bloque_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_produ",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // for_produ ::= FOR PARENIZQ asignacion ENDEXPR exprPrin ENDEXPR exprPrin PARENDER bloque_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_produ",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // for_produ ::= FOR PARENIZQ creacionasignacion ENDEXPR exprPrin ENDEXPR exprPrin PARENDER bloque_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_produ",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // while_produ ::= WHILE PARENIZQ exprPrin PARENDER bloque_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_produ",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // switch_produ ::= SWITCH PARENIZQ exprPrin PARENDER BRACEIZQ historia_produ casodefault BRACEDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("switch_produ",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // historia_produ ::= CASE factor DOSPUNTOS bloque_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("historia_produ",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // historia_produ ::= historia_produ CASE tipos DOSPUNTOS bloque_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("historia_produ",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // casodefault ::= DEFAULT DOSPUNTOS bloque_produ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("casodefault",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // casodefault ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("casodefault",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // llamadaFuncion ::= IDENTIFICADOR PARENIZQ parametrosOpcionales PARENDER ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamadaFuncion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // parametrosOpcionales ::= parametros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosOpcionales",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // parametrosOpcionales ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosOpcionales",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // parametros ::= exprPrin 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // parametros ::= parametros COMMA exprPrin 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // creacionArreglo ::= tipos IDENTIFICADOR CORCHETEIZQ NUMERO CORCHETEDER ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("creacionArreglo",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // creacionArreglo ::= tipos IDENTIFICADOR CORCHETEIZQ NUMERO CORCHETEDER ASIGNACION CORCHETEIZQ valoresArreglo CORCHETEDER ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("creacionArreglo",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // valoresArreglo ::= exprPrin 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valoresArreglo",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // valoresArreglo ::= valoresArreglo COMMA exprPrin 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valoresArreglo",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // modificacionArreglo ::= IDENTIFICADOR CORCHETEIZQ exprPrin CORCHETEDER ASIGNACION exprPrin ENDEXPR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("modificacionArreglo",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
