/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
package ParserLexer;
import java_cup.runtime.*;


action code {:
    HashMap<String, ArrayList<String>> listaTablasSimbolos = new HashMap<String, ArrayList<String>>();
    String currentHash;

    public void imprimirTablaSimbolos(){
        for (String key : listaTablasSimbolos.keySet()) {
            System.out.println("Tabla de simbolos: " + key);
            System.out.println("Valores: ");
            for (String item : listaTablasSimbolos.get(key)) {
                System.out.println(item);
            }
            System.out.println("");
        }
    }

    //escribir en archivo la tabla de simbolos
    public void escribirTablaSimbolos(String nombreArchivo){
        try {
            FileWriter myWriter = new FileWriter(nombreArchivo);
            for (String key : listaTablasSimbolos.keySet()) {
                myWriter.write("Tabla de simbolos: " + key + "\n");
                myWriter.write("Valores: \n");
                for (String item : listaTablasSimbolos.get(key)) {
                    myWriter.write(item + "\n");
                }
                myWriter.write("\n");
            }
            myWriter.close();
            System.out.println("Tabla de simbolos guardada en " + nombreArchivo);
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }
:}

parser code {:
    BasicLexerCupV lex;

    @SupressWarnings("deprecation")
    public parser(LexerCup lex){
        this.lex = lex;
        this.symbolFactory = new DefaultSymbolFactory();
    }
:}

/* define how to connect to the scanner! */
init with {: :};
scan with {: return lex.next_token(); :};

//Terminales de tipos
terminal INTEGER, FLOAT, BOOL, CHAR, STRING;

//Terminales relacionales
terminal MENOR, MENORIGUAL, MAYOR, MAYORIGUAL, IGUALDAD, DIFERENTE;

//Terminales de parentesis y llaves
terminal PARENIZQ, PARENDER, BRACEIZQ, BRACEDER, CORCHETEIZQ, CORCHETEDER;

//Terminales aritmeticos unarios 
terminal INCREMENTO, DECREMENTO;

//Terminales aritmeticos binarios
terminal SUMA, RESTA, DIVISION, MULTIPLICACION, MODULO, POTENCIA;

//Terminales operadores logicos
terminal CONJUNCION, DISYUNCION, NEGACION;

//Terminales estructuras de control de flujo
terminal IF, ELSE, FOR, WHILE, SWITCH, CASE, BREAK, RETURN, DOSPUNTOS;

//Terminales de identificadores y main
terminal IDENTIFICADOR, NUMERO, ERROR, ASIGNACION, MAIN;

//Terminales de finalizacion
terminal ENDEXPR, COMMA, COMILLA, COMILLADOBLE;

//terminales IO
terminal PRINT, READ;

//terminales booleanos
terminal TRUE, FALSE;

//terminales comentarios
terminal COMENTARIO, MULTICOMENTARIO;

//terminal de default
terminal DEFAULT;

//no terminales 
non terminal funcion, inicio, main

funciones ::= funcion
            | funciones funcion
            ;

inicio ::= funciones main
        ;

ini ::= {::} inicio {: 
imprimirTablaSimbolos();
escribirTablaSimbolos("tablaSimbolos.txt");
:}
    