
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ParserLexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 38;
  public static final int CHAR = 5;
  public static final int CASE = 35;
  public static final int DIFERENTE = 12;
  public static final int RESTA = 22;
  public static final int INTEGER = 2;
  public static final int PARENIZQ = 13;
  public static final int BRACEIZQ = 15;
  public static final int FOR = 32;
  public static final int CORCHETEIZQ = 17;
  public static final int IDENTIFICADOR = 39;
  public static final int MENORIGUAL = 8;
  public static final int IGUALDAD = 11;
  public static final int COMMA = 45;
  public static final int BOOL = 4;
  public static final int INCREMENTO = 19;
  public static final int SUMA = 21;
  public static final int MAIN = 43;
  public static final int IF = 30;
  public static final int MAYORIGUAL = 10;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int TRUE = 48;
  public static final int DECREMENTO = 20;
  public static final int error = 1;
  public static final int MODULO = 25;
  public static final int NEGACION = 29;
  public static final int MENOR = 7;
  public static final int NUMBER = 40;
  public static final int BREAK = 36;
  public static final int PARENDER = 14;
  public static final int ERROR = 41;
  public static final int ASIGNACION = 42;
  public static final int BRACEDER = 16;
  public static final int SWITCH = 34;
  public static final int MAYOR = 9;
  public static final int POTENCIA = 26;
  public static final int CORCHETEDER = 18;
  public static final int ELSE = 31;
  public static final int READ = 47;
  public static final int WHILE = 33;
  public static final int DEFAULT = 50;
  public static final int FLOAT = 3;
  public static final int CONJUNCION = 27;
  public static final int STRING = 6;
  public static final int DISYUNCION = 28;
  public static final int FALSE = 49;
  public static final int DIVISION = 23;
  public static final int PRINT = 46;
  public static final int ENDEXPR = 44;
  public static final int MULTIPLICACION = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "IGUALDAD",
  "DIFERENTE",
  "PARENIZQ",
  "PARENDER",
  "BRACEIZQ",
  "BRACEDER",
  "CORCHETEIZQ",
  "CORCHETEDER",
  "INCREMENTO",
  "DECREMENTO",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "MODULO",
  "POTENCIA",
  "CONJUNCION",
  "DISYUNCION",
  "NEGACION",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "SWITCH",
  "CASE",
  "BREAK",
  "RETURN",
  "DOSPUNTOS",
  "IDENTIFICADOR",
  "NUMBER",
  "ERROR",
  "ASIGNACION",
  "MAIN",
  "ENDEXPR",
  "COMMA",
  "PRINT",
  "READ",
  "TRUE",
  "FALSE",
  "DEFAULT"
  };
}

